version: '3.8'

services:
  starfit-webapi:
    image: ghcr.io/cesi-podometre/api-pedometer/webapi:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.express-http.rule=Host(`www.storymakerapi.fr`)"
      - "traefik.http.routers.express-http.entrypoints=websecure"
      - "traefik.http.routers.express-http.tls.certresolver=myresolver"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=User ID =postgres;Password=${POSTGRES_PASSWORD};Server=starfit-db;Port=5432;Database=starfit; Integrated Security=true;Pooling=true;
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    depends_on:
      - starfit-db
    networks:
      - frontend
      - backend
  
  migrations:
    image: ghcr.io/cesi-podometre/api-pedometer/migrations:latest
    restart: "on-failure"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=User ID =postgres;Password=${POSTGRES_PASSWORD};Server=starfit-db;Port=5432;Database=starfit; Integrated Security=true;Pooling=true;
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    depends_on:
      - starfit-webapi
    networks:
      - backend 
  
  starfit-db:
    image: "postgres:16"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=starfit
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./database/:/var/lib/postgresql/data
    networks:
      - backend

networks:
  frontend:
    external: true
    name: custom_frontend

  backend:
    external: true
    name: custom_backend