version: '3.8'

services:
  starfit-webapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=User ID =postgres;Password=${POSTGRES_PASSWORD};Server=starfit-db;Port=5432;Database=starfit; Integrated Security=true;Pooling=true;
    depends_on:
        - starfit-db
    networks:
      - starfit-db-network
        
  migrations:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: migrations
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=User ID =postgres;Password=${POSTGRES_PASSWORD};Server=starfit-db;Port=5432;Database=starfit; Integrated Security=true;Pooling=true;
    depends_on:
      - starfit-webapi
    networks:
      - starfit-db-network
      
  starfit-db:
    image: "postgres:16"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=starfit
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./database/:/var/lib/postgresql/data
    networks:
      - starfit-db-network

networks:
  starfit-db-network:
    driver: bridge