version: '3.8'

services:
  webapi:
    image: ghcr.io/clement-legay/starfit/webapi:latest
    networks: 
      - api-network
      - db-network
    ports:
      - "80:80"
    depends_on:
      - db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
  db:
    image: "postgres:16"
    restart: always
    networks:
      - db-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database/:/var/lib/postgresql/data

networks:
  api-network:
    external: true
    name: api-network
  db-network:
    external: true
    name: db-network
