// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StarFitApi.Models;

#nullable disable

namespace StarFitApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240312144357_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StarFitApi.Models.Database.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("IllustrationPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("illustration_path");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean")
                        .HasColumnName("published");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2cddf95f-14c4-468a-913d-a476f2c1b459"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3650),
                            Description = "Content 0",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3650),
                            Title = "Article 0",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3650)
                        },
                        new
                        {
                            Id = new Guid("9aa5420c-d74b-41bf-a1ac-06d58a202d8c"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3660),
                            Description = "Content 1",
                            IllustrationPath = "https://thumbs.dreamstime.com/b/bald-man-thumbs-up-26364248.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3660),
                            Title = "Article 1",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3660)
                        },
                        new
                        {
                            Id = new Guid("8be2d632-f11a-45ee-bcbf-5e2cff5e6c5d"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3670),
                            Description = "Content 2",
                            IllustrationPath = "https://previews.123rf.com/images/ambro/ambro1112/ambro111200418/11558816-businessman-with-thumbs-up.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3670),
                            Title = "Article 2",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3670)
                        },
                        new
                        {
                            Id = new Guid("8ce008af-ab55-4594-bbb8-0afec2a5e063"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3680),
                            Description = "Content 3",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3680),
                            Title = "Article 3",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3680)
                        },
                        new
                        {
                            Id = new Guid("cd07a751-670c-4ee2-aaac-b08d9639a393"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3690),
                            Description = "Content 4",
                            IllustrationPath = "https://thumbs.dreamstime.com/b/bald-man-thumbs-up-26364248.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3690),
                            Title = "Article 4",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3690)
                        },
                        new
                        {
                            Id = new Guid("5a6a109d-3583-4d0c-8a10-98a7d25fa442"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3710),
                            Description = "Content 5",
                            IllustrationPath = "https://previews.123rf.com/images/ambro/ambro1112/ambro111200418/11558816-businessman-with-thumbs-up.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3710),
                            Title = "Article 5",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3720)
                        },
                        new
                        {
                            Id = new Guid("9b0baf81-8309-4b83-b1f5-83094139f516"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3720),
                            Description = "Content 6",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3720),
                            Title = "Article 6",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3720)
                        },
                        new
                        {
                            Id = new Guid("bbd40d30-ba67-4e47-a127-3b3cbe6641ec"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3730),
                            Description = "Content 7",
                            IllustrationPath = "https://thumbs.dreamstime.com/b/bald-man-thumbs-up-26364248.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3730),
                            Title = "Article 7",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3730)
                        },
                        new
                        {
                            Id = new Guid("8d06b463-c76b-450e-bef2-794d3a902477"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3740),
                            Description = "Content 8",
                            IllustrationPath = "https://previews.123rf.com/images/ambro/ambro1112/ambro111200418/11558816-businessman-with-thumbs-up.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3740),
                            Title = "Article 8",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3740)
                        },
                        new
                        {
                            Id = new Guid("25e0f58c-9a35-4ba0-b124-ccadf54814bb"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3750),
                            Description = "Content 9",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3750),
                            Title = "Article 9",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3750)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("icon_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5289271b-e3c6-4aa4-9006-03bc8bd7993e"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3360),
                            Description = "Content 0",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 0",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3360)
                        },
                        new
                        {
                            Id = new Guid("bf797fc6-e033-4220-8575-318db36ba831"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3370),
                            Description = "Content 1",
                            IconPath = "https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM5LWltYWdlXzItbDBqOXFvd3IucG5n.png",
                            Title = "Badge 1",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3370)
                        },
                        new
                        {
                            Id = new Guid("01ae81ee-7eb3-433b-a2e4-46b5e3865adf"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3370),
                            Description = "Content 2",
                            IconPath = "https://pngimg.com/uploads/cat/cat_PNG50447.png",
                            Title = "Badge 2",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3380)
                        },
                        new
                        {
                            Id = new Guid("1da21246-c6c4-4721-a50c-80dc9bfa8098"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3380),
                            Description = "Content 3",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 3",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3380)
                        },
                        new
                        {
                            Id = new Guid("12006009-4d55-4763-a26d-8e2d624fd3c4"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3390),
                            Description = "Content 4",
                            IconPath = "https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM5LWltYWdlXzItbDBqOXFvd3IucG5n.png",
                            Title = "Badge 4",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3390)
                        },
                        new
                        {
                            Id = new Guid("5e14ccb3-dca2-45b5-94af-752602b52445"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3400),
                            Description = "Content 5",
                            IconPath = "https://pngimg.com/uploads/cat/cat_PNG50447.png",
                            Title = "Badge 5",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3400)
                        },
                        new
                        {
                            Id = new Guid("1888638c-0069-4874-81ac-3b0ca1b583a9"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3410),
                            Description = "Content 6",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 6",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3410)
                        },
                        new
                        {
                            Id = new Guid("09ad58df-b5ad-4a19-826b-0c76d838bbc8"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3420),
                            Description = "Content 7",
                            IconPath = "https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM5LWltYWdlXzItbDBqOXFvd3IucG5n.png",
                            Title = "Badge 7",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3420)
                        },
                        new
                        {
                            Id = new Guid("9a8b45d3-9acb-4298-882f-f68e798e003c"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3420),
                            Description = "Content 8",
                            IconPath = "https://pngimg.com/uploads/cat/cat_PNG50447.png",
                            Title = "Badge 8",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3430)
                        },
                        new
                        {
                            Id = new Guid("7b429312-5034-4cf0-ac86-70f4fae88857"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3430),
                            Description = "Content 9",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 9",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3430)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.BadgesToUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("ObtainedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("obtained_at");

                    b.HasKey("UserId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("BadgesToUser");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("9769ffb7-852d-4e97-80ed-19051890d5a1"),
                            BadgeId = new Guid("5289271b-e3c6-4aa4-9006-03bc8bd7993e"),
                            ObtainedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4190)
                        },
                        new
                        {
                            UserId = new Guid("f99b3654-72bd-4ce2-9540-49530d6c0804"),
                            BadgeId = new Guid("bf797fc6-e033-4220-8575-318db36ba831"),
                            ObtainedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4190)
                        },
                        new
                        {
                            UserId = new Guid("245ca322-5ef8-4ca3-9205-fbaacdf5f3c4"),
                            BadgeId = new Guid("01ae81ee-7eb3-433b-a2e4-46b5e3865adf"),
                            ObtainedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4190)
                        },
                        new
                        {
                            UserId = new Guid("2b427af7-6042-4cdf-bdf2-6753c7ab721f"),
                            BadgeId = new Guid("1da21246-c6c4-4721-a50c-80dc9bfa8098"),
                            ObtainedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4190)
                        },
                        new
                        {
                            UserId = new Guid("c6e6d055-ba56-4452-b8c1-cfe6e0485f04"),
                            BadgeId = new Guid("12006009-4d55-4763-a26d-8e2d624fd3c4"),
                            ObtainedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4200)
                        },
                        new
                        {
                            UserId = new Guid("f8a3a977-0c45-4496-985c-af3bd724bd4c"),
                            BadgeId = new Guid("5e14ccb3-dca2-45b5-94af-752602b52445"),
                            ObtainedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4200)
                        },
                        new
                        {
                            UserId = new Guid("a1293e40-19d1-46dd-8daf-71c71ae8e624"),
                            BadgeId = new Guid("1888638c-0069-4874-81ac-3b0ca1b583a9"),
                            ObtainedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4200)
                        },
                        new
                        {
                            UserId = new Guid("678b67be-9cd7-4c57-8df3-4e5882e4ae12"),
                            BadgeId = new Guid("09ad58df-b5ad-4a19-826b-0c76d838bbc8"),
                            ObtainedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4200)
                        },
                        new
                        {
                            UserId = new Guid("a98f8d20-4848-4433-a2a8-d43d566317cf"),
                            BadgeId = new Guid("9a8b45d3-9acb-4298-882f-f68e798e003c"),
                            ObtainedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4200)
                        },
                        new
                        {
                            UserId = new Guid("9d586bd6-9d56-4741-86d7-d36d705a7aa8"),
                            BadgeId = new Guid("7b429312-5034-4cf0-ac86-70f4fae88857"),
                            ObtainedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4200)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_global");

                    b.Property<int>("Objective")
                        .HasColumnType("integer")
                        .HasColumnName("objective");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.ToTable("Challenges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("766f89a2-d15a-4d96-bc07-340f008387d0"),
                            BadgeId = new Guid("5289271b-e3c6-4aa4-9006-03bc8bd7993e"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3510),
                            Description = "Content 0",
                            EndDate = new DateTime(2024, 4, 11, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3500),
                            IsGlobal = true,
                            Objective = 86071,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3480),
                            Title = "Challenge 0",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3510)
                        },
                        new
                        {
                            Id = new Guid("5a26d287-295e-4591-8363-499f1e58940e"),
                            BadgeId = new Guid("bf797fc6-e033-4220-8575-318db36ba831"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3530),
                            Description = "Content 1",
                            EndDate = new DateTime(2024, 4, 11, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3530),
                            IsGlobal = false,
                            Objective = 96847,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3520),
                            Title = "Challenge 1",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3530)
                        },
                        new
                        {
                            Id = new Guid("276710bf-c82e-4036-b20f-cbef361a7abd"),
                            BadgeId = new Guid("01ae81ee-7eb3-433b-a2e4-46b5e3865adf"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3540),
                            Description = "Content 2",
                            EndDate = new DateTime(2024, 4, 11, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3540),
                            IsGlobal = true,
                            Objective = 94902,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3540),
                            Title = "Challenge 2",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3540)
                        },
                        new
                        {
                            Id = new Guid("fed20dd5-fa76-4dcb-a4a9-d33fbb97e348"),
                            BadgeId = new Guid("1da21246-c6c4-4721-a50c-80dc9bfa8098"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3550),
                            Description = "Content 3",
                            EndDate = new DateTime(2024, 4, 11, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3550),
                            IsGlobal = false,
                            Objective = 55021,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3550),
                            Title = "Challenge 3",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3550)
                        },
                        new
                        {
                            Id = new Guid("3343fb33-772d-469f-82aa-de8e061eb4af"),
                            BadgeId = new Guid("12006009-4d55-4763-a26d-8e2d624fd3c4"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3560),
                            Description = "Content 4",
                            EndDate = new DateTime(2024, 4, 11, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3560),
                            IsGlobal = true,
                            Objective = 10797,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3560),
                            Title = "Challenge 4",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3560)
                        },
                        new
                        {
                            Id = new Guid("f37c9b37-f0a8-4891-89a3-c77af3e03e00"),
                            BadgeId = new Guid("5e14ccb3-dca2-45b5-94af-752602b52445"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3580),
                            Description = "Content 5",
                            EndDate = new DateTime(2024, 4, 11, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3580),
                            IsGlobal = false,
                            Objective = 98028,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3570),
                            Title = "Challenge 5",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3580)
                        },
                        new
                        {
                            Id = new Guid("8bc65ecc-627d-4015-81fa-546363fe6648"),
                            BadgeId = new Guid("1888638c-0069-4874-81ac-3b0ca1b583a9"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3590),
                            Description = "Content 6",
                            EndDate = new DateTime(2024, 4, 11, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3590),
                            IsGlobal = true,
                            Objective = 24152,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3590),
                            Title = "Challenge 6",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3590)
                        },
                        new
                        {
                            Id = new Guid("2355ddf2-b26a-4a53-8458-88706993b759"),
                            BadgeId = new Guid("09ad58df-b5ad-4a19-826b-0c76d838bbc8"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3600),
                            Description = "Content 7",
                            EndDate = new DateTime(2024, 4, 11, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3600),
                            IsGlobal = false,
                            Objective = 98634,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3600),
                            Title = "Challenge 7",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3600)
                        },
                        new
                        {
                            Id = new Guid("1eeb354b-baa0-4354-880d-a06eaf1f1f63"),
                            BadgeId = new Guid("9a8b45d3-9acb-4298-882f-f68e798e003c"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3610),
                            Description = "Content 8",
                            EndDate = new DateTime(2024, 4, 11, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3610),
                            IsGlobal = true,
                            Objective = 87002,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3610),
                            Title = "Challenge 8",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3610)
                        },
                        new
                        {
                            Id = new Guid("6411679f-1e16-48ff-9432-812b76f5489b"),
                            BadgeId = new Guid("7b429312-5034-4cf0-ac86-70f4fae88857"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3620),
                            Description = "Content 9",
                            EndDate = new DateTime(2024, 4, 11, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3620),
                            IsGlobal = false,
                            Objective = 51079,
                            StartDate = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3620),
                            Title = "Challenge 9",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3630)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.DayOfWalk", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Steps")
                        .HasColumnType("integer")
                        .HasColumnName("steps");

                    b.HasKey("Date", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("DayOfWalk");

                    b.HasData(
                        new
                        {
                            Date = new DateTime(2023, 12, 3, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3800),
                            UserId = new Guid("9769ffb7-852d-4e97-80ed-19051890d5a1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 4, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3810),
                            UserId = new Guid("f99b3654-72bd-4ce2-9540-49530d6c0804"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 5, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3810),
                            UserId = new Guid("245ca322-5ef8-4ca3-9205-fbaacdf5f3c4"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 6, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3810),
                            UserId = new Guid("2b427af7-6042-4cdf-bdf2-6753c7ab721f"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 7, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3820),
                            UserId = new Guid("c6e6d055-ba56-4452-b8c1-cfe6e0485f04"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 8, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3820),
                            UserId = new Guid("f8a3a977-0c45-4496-985c-af3bd724bd4c"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 9, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3820),
                            UserId = new Guid("a1293e40-19d1-46dd-8daf-71c71ae8e624"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 10, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3830),
                            UserId = new Guid("678b67be-9cd7-4c57-8df3-4e5882e4ae12"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 11, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3830),
                            UserId = new Guid("a98f8d20-4848-4433-a2a8-d43d566317cf"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3840),
                            UserId = new Guid("9d586bd6-9d56-4741-86d7-d36d705a7aa8"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 13, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3840),
                            UserId = new Guid("9769ffb7-852d-4e97-80ed-19051890d5a1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 14, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3840),
                            UserId = new Guid("f99b3654-72bd-4ce2-9540-49530d6c0804"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 15, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3850),
                            UserId = new Guid("245ca322-5ef8-4ca3-9205-fbaacdf5f3c4"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 16, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3850),
                            UserId = new Guid("2b427af7-6042-4cdf-bdf2-6753c7ab721f"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 17, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3850),
                            UserId = new Guid("c6e6d055-ba56-4452-b8c1-cfe6e0485f04"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 18, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3860),
                            UserId = new Guid("f8a3a977-0c45-4496-985c-af3bd724bd4c"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 19, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3860),
                            UserId = new Guid("a1293e40-19d1-46dd-8daf-71c71ae8e624"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 20, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3860),
                            UserId = new Guid("678b67be-9cd7-4c57-8df3-4e5882e4ae12"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 21, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3870),
                            UserId = new Guid("a98f8d20-4848-4433-a2a8-d43d566317cf"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 22, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3870),
                            UserId = new Guid("9d586bd6-9d56-4741-86d7-d36d705a7aa8"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 23, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3870),
                            UserId = new Guid("9769ffb7-852d-4e97-80ed-19051890d5a1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 24, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3880),
                            UserId = new Guid("f99b3654-72bd-4ce2-9540-49530d6c0804"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 25, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3880),
                            UserId = new Guid("245ca322-5ef8-4ca3-9205-fbaacdf5f3c4"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 26, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3890),
                            UserId = new Guid("2b427af7-6042-4cdf-bdf2-6753c7ab721f"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 27, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3890),
                            UserId = new Guid("c6e6d055-ba56-4452-b8c1-cfe6e0485f04"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 28, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3890),
                            UserId = new Guid("f8a3a977-0c45-4496-985c-af3bd724bd4c"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 29, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3900),
                            UserId = new Guid("a1293e40-19d1-46dd-8daf-71c71ae8e624"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 30, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3900),
                            UserId = new Guid("678b67be-9cd7-4c57-8df3-4e5882e4ae12"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 31, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3900),
                            UserId = new Guid("a98f8d20-4848-4433-a2a8-d43d566317cf"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 1, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3910),
                            UserId = new Guid("9d586bd6-9d56-4741-86d7-d36d705a7aa8"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 2, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3910),
                            UserId = new Guid("9769ffb7-852d-4e97-80ed-19051890d5a1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 3, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3910),
                            UserId = new Guid("f99b3654-72bd-4ce2-9540-49530d6c0804"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 4, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3920),
                            UserId = new Guid("245ca322-5ef8-4ca3-9205-fbaacdf5f3c4"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 5, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3920),
                            UserId = new Guid("2b427af7-6042-4cdf-bdf2-6753c7ab721f"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 6, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3920),
                            UserId = new Guid("c6e6d055-ba56-4452-b8c1-cfe6e0485f04"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 7, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3930),
                            UserId = new Guid("f8a3a977-0c45-4496-985c-af3bd724bd4c"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 8, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3930),
                            UserId = new Guid("a1293e40-19d1-46dd-8daf-71c71ae8e624"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 9, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3930),
                            UserId = new Guid("678b67be-9cd7-4c57-8df3-4e5882e4ae12"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 10, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3940),
                            UserId = new Guid("a98f8d20-4848-4433-a2a8-d43d566317cf"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 11, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3940),
                            UserId = new Guid("9d586bd6-9d56-4741-86d7-d36d705a7aa8"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3950),
                            UserId = new Guid("9769ffb7-852d-4e97-80ed-19051890d5a1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 13, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3950),
                            UserId = new Guid("f99b3654-72bd-4ce2-9540-49530d6c0804"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 14, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3950),
                            UserId = new Guid("245ca322-5ef8-4ca3-9205-fbaacdf5f3c4"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 15, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3960),
                            UserId = new Guid("2b427af7-6042-4cdf-bdf2-6753c7ab721f"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 16, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3960),
                            UserId = new Guid("c6e6d055-ba56-4452-b8c1-cfe6e0485f04"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 17, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3960),
                            UserId = new Guid("f8a3a977-0c45-4496-985c-af3bd724bd4c"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 18, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3970),
                            UserId = new Guid("a1293e40-19d1-46dd-8daf-71c71ae8e624"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 19, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3970),
                            UserId = new Guid("678b67be-9cd7-4c57-8df3-4e5882e4ae12"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 20, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3970),
                            UserId = new Guid("a98f8d20-4848-4433-a2a8-d43d566317cf"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 21, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3980),
                            UserId = new Guid("9d586bd6-9d56-4741-86d7-d36d705a7aa8"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 22, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3980),
                            UserId = new Guid("9769ffb7-852d-4e97-80ed-19051890d5a1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 23, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3980),
                            UserId = new Guid("f99b3654-72bd-4ce2-9540-49530d6c0804"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 24, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3990),
                            UserId = new Guid("245ca322-5ef8-4ca3-9205-fbaacdf5f3c4"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 25, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3990),
                            UserId = new Guid("2b427af7-6042-4cdf-bdf2-6753c7ab721f"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 26, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3990),
                            UserId = new Guid("c6e6d055-ba56-4452-b8c1-cfe6e0485f04"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 27, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4000),
                            UserId = new Guid("f8a3a977-0c45-4496-985c-af3bd724bd4c"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 28, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4000),
                            UserId = new Guid("a1293e40-19d1-46dd-8daf-71c71ae8e624"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 29, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4000),
                            UserId = new Guid("678b67be-9cd7-4c57-8df3-4e5882e4ae12"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 30, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4010),
                            UserId = new Guid("a98f8d20-4848-4433-a2a8-d43d566317cf"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 31, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4010),
                            UserId = new Guid("9d586bd6-9d56-4741-86d7-d36d705a7aa8"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 1, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4020),
                            UserId = new Guid("9769ffb7-852d-4e97-80ed-19051890d5a1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 2, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4020),
                            UserId = new Guid("f99b3654-72bd-4ce2-9540-49530d6c0804"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 3, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4020),
                            UserId = new Guid("245ca322-5ef8-4ca3-9205-fbaacdf5f3c4"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 4, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4030),
                            UserId = new Guid("2b427af7-6042-4cdf-bdf2-6753c7ab721f"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 5, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4030),
                            UserId = new Guid("c6e6d055-ba56-4452-b8c1-cfe6e0485f04"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 6, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4030),
                            UserId = new Guid("f8a3a977-0c45-4496-985c-af3bd724bd4c"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 7, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4040),
                            UserId = new Guid("a1293e40-19d1-46dd-8daf-71c71ae8e624"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 8, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4040),
                            UserId = new Guid("678b67be-9cd7-4c57-8df3-4e5882e4ae12"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 9, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4040),
                            UserId = new Guid("a98f8d20-4848-4433-a2a8-d43d566317cf"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 10, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4050),
                            UserId = new Guid("9d586bd6-9d56-4741-86d7-d36d705a7aa8"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 11, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4050),
                            UserId = new Guid("9769ffb7-852d-4e97-80ed-19051890d5a1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4050),
                            UserId = new Guid("f99b3654-72bd-4ce2-9540-49530d6c0804"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 13, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4060),
                            UserId = new Guid("245ca322-5ef8-4ca3-9205-fbaacdf5f3c4"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 14, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4060),
                            UserId = new Guid("2b427af7-6042-4cdf-bdf2-6753c7ab721f"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 15, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4060),
                            UserId = new Guid("c6e6d055-ba56-4452-b8c1-cfe6e0485f04"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 16, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4070),
                            UserId = new Guid("f8a3a977-0c45-4496-985c-af3bd724bd4c"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 17, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4070),
                            UserId = new Guid("a1293e40-19d1-46dd-8daf-71c71ae8e624"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 18, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4080),
                            UserId = new Guid("678b67be-9cd7-4c57-8df3-4e5882e4ae12"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 19, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4080),
                            UserId = new Guid("a98f8d20-4848-4433-a2a8-d43d566317cf"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 20, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4080),
                            UserId = new Guid("9d586bd6-9d56-4741-86d7-d36d705a7aa8"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 21, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4090),
                            UserId = new Guid("9769ffb7-852d-4e97-80ed-19051890d5a1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 22, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4090),
                            UserId = new Guid("f99b3654-72bd-4ce2-9540-49530d6c0804"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 23, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4090),
                            UserId = new Guid("245ca322-5ef8-4ca3-9205-fbaacdf5f3c4"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 24, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4100),
                            UserId = new Guid("2b427af7-6042-4cdf-bdf2-6753c7ab721f"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 25, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4100),
                            UserId = new Guid("c6e6d055-ba56-4452-b8c1-cfe6e0485f04"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 26, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4110),
                            UserId = new Guid("f8a3a977-0c45-4496-985c-af3bd724bd4c"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 27, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4110),
                            UserId = new Guid("a1293e40-19d1-46dd-8daf-71c71ae8e624"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 28, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4110),
                            UserId = new Guid("678b67be-9cd7-4c57-8df3-4e5882e4ae12"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 29, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4120),
                            UserId = new Guid("a98f8d20-4848-4433-a2a8-d43d566317cf"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 1, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4120),
                            UserId = new Guid("9d586bd6-9d56-4741-86d7-d36d705a7aa8"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 2, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4120),
                            UserId = new Guid("9769ffb7-852d-4e97-80ed-19051890d5a1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 3, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4130),
                            UserId = new Guid("f99b3654-72bd-4ce2-9540-49530d6c0804"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 4, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4130),
                            UserId = new Guid("245ca322-5ef8-4ca3-9205-fbaacdf5f3c4"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 5, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4130),
                            UserId = new Guid("2b427af7-6042-4cdf-bdf2-6753c7ab721f"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 6, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4140),
                            UserId = new Guid("c6e6d055-ba56-4452-b8c1-cfe6e0485f04"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 7, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4140),
                            UserId = new Guid("f8a3a977-0c45-4496-985c-af3bd724bd4c"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 8, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4140),
                            UserId = new Guid("a1293e40-19d1-46dd-8daf-71c71ae8e624"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 9, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4150),
                            UserId = new Guid("678b67be-9cd7-4c57-8df3-4e5882e4ae12"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 10, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4150),
                            UserId = new Guid("a98f8d20-4848-4433-a2a8-d43d566317cf"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 11, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(4150),
                            UserId = new Guid("9d586bd6-9d56-4741-86d7-d36d705a7aa8"),
                            Steps = 1000
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9769ffb7-852d-4e97-80ed-19051890d5a1"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3100),
                            Identifier = "user0",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3170)
                        },
                        new
                        {
                            Id = new Guid("f99b3654-72bd-4ce2-9540-49530d6c0804"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3180),
                            Identifier = "user1",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3180)
                        },
                        new
                        {
                            Id = new Guid("245ca322-5ef8-4ca3-9205-fbaacdf5f3c4"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3190),
                            Identifier = "user2",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3190)
                        },
                        new
                        {
                            Id = new Guid("2b427af7-6042-4cdf-bdf2-6753c7ab721f"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3200),
                            Identifier = "user3",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3200)
                        },
                        new
                        {
                            Id = new Guid("c6e6d055-ba56-4452-b8c1-cfe6e0485f04"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3200),
                            Identifier = "user4",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3200)
                        },
                        new
                        {
                            Id = new Guid("f8a3a977-0c45-4496-985c-af3bd724bd4c"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3210),
                            Identifier = "user5",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3210)
                        },
                        new
                        {
                            Id = new Guid("a1293e40-19d1-46dd-8daf-71c71ae8e624"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3220),
                            Identifier = "user6",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3220)
                        },
                        new
                        {
                            Id = new Guid("678b67be-9cd7-4c57-8df3-4e5882e4ae12"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3230),
                            Identifier = "user7",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3230)
                        },
                        new
                        {
                            Id = new Guid("a98f8d20-4848-4433-a2a8-d43d566317cf"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3240),
                            Identifier = "user8",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3240)
                        },
                        new
                        {
                            Id = new Guid("9d586bd6-9d56-4741-86d7-d36d705a7aa8"),
                            CreatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3250),
                            Identifier = "user9",
                            UpdatedAt = new DateTime(2024, 3, 12, 15, 43, 57, 883, DateTimeKind.Local).AddTicks(3250)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Badge", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.User", null)
                        .WithMany("Badges")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.BadgesToUser", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarFitApi.Models.Database.User", "User")
                        .WithMany("BadgesToUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Challenge", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.Badge", "Badge")
                        .WithMany("Challenges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.DayOfWalk", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.User", "User")
                        .WithMany("DaysOfWalk")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Badge", b =>
                {
                    b.Navigation("Challenges");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.User", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("BadgesToUsers");

                    b.Navigation("DaysOfWalk");
                });
#pragma warning restore 612, 618
        }
    }
}
