// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StarFitApi.Models;

#nullable disable

namespace StarFitApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240314122031_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StarFitApi.Models.Database.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_path");

                    b.Property<string>("IllustrationPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("illustration_path");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean")
                        .HasColumnName("published");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc9aa619-755f-42bb-b17a-ba36d4c31a0a"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9320),
                            Description = "Content 0",
                            FilePath = "https://lyc-jules-ferry.fr/wp-content/uploads/2021/03/6Cadavre-exquis-ecrit-2.pdf",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9320),
                            Title = "Article 0",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9320)
                        },
                        new
                        {
                            Id = new Guid("39667f57-4037-42c7-ab8f-3a474d57a62a"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9330),
                            Description = "Content 1",
                            FilePath = "https://organzo.ca/wp-content/uploads/2013/05/FR_eggplant.pdf",
                            IllustrationPath = "https://thumbs.dreamstime.com/b/bald-man-thumbs-up-26364248.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9330),
                            Title = "Article 1",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9330)
                        },
                        new
                        {
                            Id = new Guid("fd4d18fc-cb89-4653-be13-d1f8d0ac8586"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9340),
                            Description = "Content 2",
                            FilePath = "https://www.icao.int/WACAF/Documents/Meetings/2015/Surveillance%20h%C3%A9listations/1.2%20Technique%20de%20l%27h%C3%A9licopt%C3%A8re.pdf",
                            IllustrationPath = "https://previews.123rf.com/images/ambro/ambro1112/ambro111200418/11558816-businessman-with-thumbs-up.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9340),
                            Title = "Article 2",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9340)
                        },
                        new
                        {
                            Id = new Guid("39bd6d10-4783-4c81-b122-cc8326004e5b"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9350),
                            Description = "Content 3",
                            FilePath = "https://lyc-jules-ferry.fr/wp-content/uploads/2021/03/6Cadavre-exquis-ecrit-2.pdf",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9350),
                            Title = "Article 3",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9350)
                        },
                        new
                        {
                            Id = new Guid("5ce64891-96ff-4dc3-b70a-1d377c376804"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9350),
                            Description = "Content 4",
                            FilePath = "https://organzo.ca/wp-content/uploads/2013/05/FR_eggplant.pdf",
                            IllustrationPath = "https://thumbs.dreamstime.com/b/bald-man-thumbs-up-26364248.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9350),
                            Title = "Article 4",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9360)
                        },
                        new
                        {
                            Id = new Guid("700a2332-3789-4b89-9d3f-e4883cef55ce"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9360),
                            Description = "Content 5",
                            FilePath = "https://www.icao.int/WACAF/Documents/Meetings/2015/Surveillance%20h%C3%A9listations/1.2%20Technique%20de%20l%27h%C3%A9licopt%C3%A8re.pdf",
                            IllustrationPath = "https://previews.123rf.com/images/ambro/ambro1112/ambro111200418/11558816-businessman-with-thumbs-up.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9360),
                            Title = "Article 5",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9360)
                        },
                        new
                        {
                            Id = new Guid("a3526366-8fa6-4347-ba6f-9c5e4c6c2a0b"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9370),
                            Description = "Content 6",
                            FilePath = "https://lyc-jules-ferry.fr/wp-content/uploads/2021/03/6Cadavre-exquis-ecrit-2.pdf",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9370),
                            Title = "Article 6",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9370)
                        },
                        new
                        {
                            Id = new Guid("d228e337-3a72-4020-b1a0-2ca46a20a18d"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9380),
                            Description = "Content 7",
                            FilePath = "https://organzo.ca/wp-content/uploads/2013/05/FR_eggplant.pdf",
                            IllustrationPath = "https://thumbs.dreamstime.com/b/bald-man-thumbs-up-26364248.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9380),
                            Title = "Article 7",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9380)
                        },
                        new
                        {
                            Id = new Guid("aa0dccf9-583e-47c3-8aa9-f1018c8590ef"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9390),
                            Description = "Content 8",
                            FilePath = "https://www.icao.int/WACAF/Documents/Meetings/2015/Surveillance%20h%C3%A9listations/1.2%20Technique%20de%20l%27h%C3%A9licopt%C3%A8re.pdf",
                            IllustrationPath = "https://previews.123rf.com/images/ambro/ambro1112/ambro111200418/11558816-businessman-with-thumbs-up.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9390),
                            Title = "Article 8",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9390)
                        },
                        new
                        {
                            Id = new Guid("507ef10b-2b2f-48b2-a049-0efad5379fe1"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9400),
                            Description = "Content 9",
                            FilePath = "https://lyc-jules-ferry.fr/wp-content/uploads/2021/03/6Cadavre-exquis-ecrit-2.pdf",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9400),
                            Title = "Article 9",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9400)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("icon_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("869c6c62-be8a-4a25-bdf7-25a389e58175"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9000),
                            Description = "Content 0",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 0",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9000)
                        },
                        new
                        {
                            Id = new Guid("572f8398-10e2-45c4-b833-e90ac3762d05"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9010),
                            Description = "Content 1",
                            IconPath = "https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM5LWltYWdlXzItbDBqOXFvd3IucG5n.png",
                            Title = "Badge 1",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9010)
                        },
                        new
                        {
                            Id = new Guid("604f0c91-5c81-4940-8181-3a9f6ffa4a24"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9020),
                            Description = "Content 2",
                            IconPath = "https://pngimg.com/uploads/cat/cat_PNG50447.png",
                            Title = "Badge 2",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9020)
                        },
                        new
                        {
                            Id = new Guid("9a8244c8-b88c-4204-a4f3-a103fa2d83f0"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9020),
                            Description = "Content 3",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 3",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9020)
                        },
                        new
                        {
                            Id = new Guid("1e79fa82-5e4e-4df5-8d9d-20b5e5009e9a"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9030),
                            Description = "Content 4",
                            IconPath = "https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM5LWltYWdlXzItbDBqOXFvd3IucG5n.png",
                            Title = "Badge 4",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9030)
                        },
                        new
                        {
                            Id = new Guid("9bc51a82-fd3f-4c7b-a9f0-90e4ff8f63aa"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9040),
                            Description = "Content 5",
                            IconPath = "https://pngimg.com/uploads/cat/cat_PNG50447.png",
                            Title = "Badge 5",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9040)
                        },
                        new
                        {
                            Id = new Guid("0d38dca0-9eef-4773-93c7-28df526522e1"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9050),
                            Description = "Content 6",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 6",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9050)
                        },
                        new
                        {
                            Id = new Guid("b5c0f1d8-4159-4c19-ab8f-9beabc77c437"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9060),
                            Description = "Content 7",
                            IconPath = "https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM5LWltYWdlXzItbDBqOXFvd3IucG5n.png",
                            Title = "Badge 7",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9060)
                        },
                        new
                        {
                            Id = new Guid("ce63f9e8-7c52-4065-9a5f-54793840d309"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9060),
                            Description = "Content 8",
                            IconPath = "https://pngimg.com/uploads/cat/cat_PNG50447.png",
                            Title = "Badge 8",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9070)
                        },
                        new
                        {
                            Id = new Guid("ccf67717-15f2-4d88-ad2c-35ac438a790e"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9070),
                            Description = "Content 9",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 9",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9070)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.BadgesToUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("ObtainedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("obtained_at");

                    b.HasKey("UserId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("BadgesToUser");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("65892d8c-be91-4bf0-afd4-753715e49bfe"),
                            BadgeId = new Guid("869c6c62-be8a-4a25-bdf7-25a389e58175"),
                            ObtainedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9570)
                        },
                        new
                        {
                            UserId = new Guid("cb30ba49-7982-46fb-95a7-35331c531752"),
                            BadgeId = new Guid("572f8398-10e2-45c4-b833-e90ac3762d05"),
                            ObtainedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9570)
                        },
                        new
                        {
                            UserId = new Guid("7e3f0fa0-a9f6-4a7e-81cc-1af71768cf5a"),
                            BadgeId = new Guid("604f0c91-5c81-4940-8181-3a9f6ffa4a24"),
                            ObtainedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9570)
                        },
                        new
                        {
                            UserId = new Guid("f6471fd8-80df-4ced-b8bd-83a69ae8db25"),
                            BadgeId = new Guid("9a8244c8-b88c-4204-a4f3-a103fa2d83f0"),
                            ObtainedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9580)
                        },
                        new
                        {
                            UserId = new Guid("f4dd1a74-89f9-40f6-830c-a3ed1fd87000"),
                            BadgeId = new Guid("1e79fa82-5e4e-4df5-8d9d-20b5e5009e9a"),
                            ObtainedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9590)
                        },
                        new
                        {
                            UserId = new Guid("62888c3c-bdbe-4f38-8ddd-4aad542b5343"),
                            BadgeId = new Guid("9bc51a82-fd3f-4c7b-a9f0-90e4ff8f63aa"),
                            ObtainedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9590)
                        },
                        new
                        {
                            UserId = new Guid("b12707e1-0825-4f28-a393-baead7b33cbd"),
                            BadgeId = new Guid("0d38dca0-9eef-4773-93c7-28df526522e1"),
                            ObtainedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9590)
                        },
                        new
                        {
                            UserId = new Guid("cb54e72f-3b57-4911-8247-f7479172598e"),
                            BadgeId = new Guid("b5c0f1d8-4159-4c19-ab8f-9beabc77c437"),
                            ObtainedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9600)
                        },
                        new
                        {
                            UserId = new Guid("a61d4bd2-0b4c-4255-9643-a98a934f4fd9"),
                            BadgeId = new Guid("ce63f9e8-7c52-4065-9a5f-54793840d309"),
                            ObtainedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9600)
                        },
                        new
                        {
                            UserId = new Guid("aa2d1d4e-a1e9-4622-b7ec-2974ea4d7f88"),
                            BadgeId = new Guid("ccf67717-15f2-4d88-ad2c-35ac438a790e"),
                            ObtainedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9600)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_global");

                    b.Property<int>("Objective")
                        .HasColumnType("integer")
                        .HasColumnName("objective");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.ToTable("Challenges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1bbbb09-ab8c-4d2e-933d-004d91d2271e"),
                            BadgeId = new Guid("869c6c62-be8a-4a25-bdf7-25a389e58175"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9130),
                            Description = "Content 0",
                            EndDate = new DateTime(2024, 4, 13, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9120),
                            IsGlobal = true,
                            Objective = 51147,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9120),
                            Title = "Challenge 0",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9130)
                        },
                        new
                        {
                            Id = new Guid("809ef97f-1316-4890-9400-2dba94cdce40"),
                            BadgeId = new Guid("572f8398-10e2-45c4-b833-e90ac3762d05"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9140),
                            Description = "Content 1",
                            EndDate = new DateTime(2024, 4, 13, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9140),
                            IsGlobal = false,
                            Objective = 2345,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9140),
                            Title = "Challenge 1",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9140)
                        },
                        new
                        {
                            Id = new Guid("13c5a2cf-393a-4dce-8cf4-79f36d93b867"),
                            BadgeId = new Guid("604f0c91-5c81-4940-8181-3a9f6ffa4a24"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9200),
                            Description = "Content 2",
                            EndDate = new DateTime(2024, 4, 13, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9200),
                            IsGlobal = true,
                            Objective = 50773,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9200),
                            Title = "Challenge 2",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9200)
                        },
                        new
                        {
                            Id = new Guid("588e0c6e-710e-485f-9257-8d5575c05dfd"),
                            BadgeId = new Guid("9a8244c8-b88c-4204-a4f3-a103fa2d83f0"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9210),
                            Description = "Content 3",
                            EndDate = new DateTime(2024, 4, 13, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9210),
                            IsGlobal = false,
                            Objective = 94919,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9210),
                            Title = "Challenge 3",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9210)
                        },
                        new
                        {
                            Id = new Guid("2c75963c-ce6a-4773-af9d-0c579652e8d1"),
                            BadgeId = new Guid("1e79fa82-5e4e-4df5-8d9d-20b5e5009e9a"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9220),
                            Description = "Content 4",
                            EndDate = new DateTime(2024, 4, 13, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9220),
                            IsGlobal = true,
                            Objective = 84787,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9220),
                            Title = "Challenge 4",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9230)
                        },
                        new
                        {
                            Id = new Guid("2e9c76a8-6910-4e19-ab27-ddb31e4bdc34"),
                            BadgeId = new Guid("9bc51a82-fd3f-4c7b-a9f0-90e4ff8f63aa"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9240),
                            Description = "Content 5",
                            EndDate = new DateTime(2024, 4, 13, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9240),
                            IsGlobal = false,
                            Objective = 44267,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9240),
                            Title = "Challenge 5",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9240)
                        },
                        new
                        {
                            Id = new Guid("3aa5fda0-5981-40fd-9f64-17a868e97f94"),
                            BadgeId = new Guid("0d38dca0-9eef-4773-93c7-28df526522e1"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9250),
                            Description = "Content 6",
                            EndDate = new DateTime(2024, 4, 13, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9250),
                            IsGlobal = true,
                            Objective = 70368,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9250),
                            Title = "Challenge 6",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9250)
                        },
                        new
                        {
                            Id = new Guid("a73517d3-987d-4b66-bb9c-6608b6631f73"),
                            BadgeId = new Guid("b5c0f1d8-4159-4c19-ab8f-9beabc77c437"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9260),
                            Description = "Content 7",
                            EndDate = new DateTime(2024, 4, 13, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9260),
                            IsGlobal = false,
                            Objective = 99167,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9260),
                            Title = "Challenge 7",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9260)
                        },
                        new
                        {
                            Id = new Guid("53e680e6-ba9d-422e-bb39-534f43231dcc"),
                            BadgeId = new Guid("ce63f9e8-7c52-4065-9a5f-54793840d309"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9270),
                            Description = "Content 8",
                            EndDate = new DateTime(2024, 4, 13, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9270),
                            IsGlobal = true,
                            Objective = 40380,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9270),
                            Title = "Challenge 8",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9270)
                        },
                        new
                        {
                            Id = new Guid("ef583f87-01b6-4f21-96a3-0664e51f182b"),
                            BadgeId = new Guid("ccf67717-15f2-4d88-ad2c-35ac438a790e"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9290),
                            Description = "Content 9",
                            EndDate = new DateTime(2024, 4, 13, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9290),
                            IsGlobal = false,
                            Objective = 75817,
                            StartDate = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9280),
                            Title = "Challenge 9",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9290)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.DayOfWalk", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Steps")
                        .HasColumnType("integer")
                        .HasColumnName("steps");

                    b.HasKey("Date", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("DayOfWalk");

                    b.HasData(
                        new
                        {
                            Date = new DateTime(2023, 12, 5, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9420),
                            UserId = new Guid("65892d8c-be91-4bf0-afd4-753715e49bfe"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 6, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9420),
                            UserId = new Guid("cb30ba49-7982-46fb-95a7-35331c531752"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 7, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9430),
                            UserId = new Guid("7e3f0fa0-a9f6-4a7e-81cc-1af71768cf5a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 8, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9430),
                            UserId = new Guid("f6471fd8-80df-4ced-b8bd-83a69ae8db25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 9, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9430),
                            UserId = new Guid("f4dd1a74-89f9-40f6-830c-a3ed1fd87000"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 10, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9430),
                            UserId = new Guid("62888c3c-bdbe-4f38-8ddd-4aad542b5343"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 11, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9430),
                            UserId = new Guid("b12707e1-0825-4f28-a393-baead7b33cbd"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 12, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9430),
                            UserId = new Guid("cb54e72f-3b57-4911-8247-f7479172598e"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 13, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9430),
                            UserId = new Guid("a61d4bd2-0b4c-4255-9643-a98a934f4fd9"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9430),
                            UserId = new Guid("aa2d1d4e-a1e9-4622-b7ec-2974ea4d7f88"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 15, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9430),
                            UserId = new Guid("65892d8c-be91-4bf0-afd4-753715e49bfe"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 16, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9440),
                            UserId = new Guid("cb30ba49-7982-46fb-95a7-35331c531752"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 17, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9440),
                            UserId = new Guid("7e3f0fa0-a9f6-4a7e-81cc-1af71768cf5a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 18, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9440),
                            UserId = new Guid("f6471fd8-80df-4ced-b8bd-83a69ae8db25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 19, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9440),
                            UserId = new Guid("f4dd1a74-89f9-40f6-830c-a3ed1fd87000"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 20, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9440),
                            UserId = new Guid("62888c3c-bdbe-4f38-8ddd-4aad542b5343"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 21, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9440),
                            UserId = new Guid("b12707e1-0825-4f28-a393-baead7b33cbd"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 22, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9440),
                            UserId = new Guid("cb54e72f-3b57-4911-8247-f7479172598e"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 23, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9440),
                            UserId = new Guid("a61d4bd2-0b4c-4255-9643-a98a934f4fd9"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 24, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9440),
                            UserId = new Guid("aa2d1d4e-a1e9-4622-b7ec-2974ea4d7f88"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 25, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9440),
                            UserId = new Guid("65892d8c-be91-4bf0-afd4-753715e49bfe"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 26, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9450),
                            UserId = new Guid("cb30ba49-7982-46fb-95a7-35331c531752"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 27, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9450),
                            UserId = new Guid("7e3f0fa0-a9f6-4a7e-81cc-1af71768cf5a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 28, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9450),
                            UserId = new Guid("f6471fd8-80df-4ced-b8bd-83a69ae8db25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 29, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9450),
                            UserId = new Guid("f4dd1a74-89f9-40f6-830c-a3ed1fd87000"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 30, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9450),
                            UserId = new Guid("62888c3c-bdbe-4f38-8ddd-4aad542b5343"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 31, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9450),
                            UserId = new Guid("b12707e1-0825-4f28-a393-baead7b33cbd"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 1, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9450),
                            UserId = new Guid("cb54e72f-3b57-4911-8247-f7479172598e"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 2, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9450),
                            UserId = new Guid("a61d4bd2-0b4c-4255-9643-a98a934f4fd9"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 3, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9450),
                            UserId = new Guid("aa2d1d4e-a1e9-4622-b7ec-2974ea4d7f88"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 4, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9450),
                            UserId = new Guid("65892d8c-be91-4bf0-afd4-753715e49bfe"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 5, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9450),
                            UserId = new Guid("cb30ba49-7982-46fb-95a7-35331c531752"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 6, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9460),
                            UserId = new Guid("7e3f0fa0-a9f6-4a7e-81cc-1af71768cf5a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 7, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9460),
                            UserId = new Guid("f6471fd8-80df-4ced-b8bd-83a69ae8db25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 8, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9460),
                            UserId = new Guid("f4dd1a74-89f9-40f6-830c-a3ed1fd87000"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 9, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9460),
                            UserId = new Guid("62888c3c-bdbe-4f38-8ddd-4aad542b5343"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 10, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9460),
                            UserId = new Guid("b12707e1-0825-4f28-a393-baead7b33cbd"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 11, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9460),
                            UserId = new Guid("cb54e72f-3b57-4911-8247-f7479172598e"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 12, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9460),
                            UserId = new Guid("a61d4bd2-0b4c-4255-9643-a98a934f4fd9"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 13, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9460),
                            UserId = new Guid("aa2d1d4e-a1e9-4622-b7ec-2974ea4d7f88"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9470),
                            UserId = new Guid("65892d8c-be91-4bf0-afd4-753715e49bfe"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 15, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9470),
                            UserId = new Guid("cb30ba49-7982-46fb-95a7-35331c531752"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 16, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9470),
                            UserId = new Guid("7e3f0fa0-a9f6-4a7e-81cc-1af71768cf5a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 17, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9470),
                            UserId = new Guid("f6471fd8-80df-4ced-b8bd-83a69ae8db25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 18, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9470),
                            UserId = new Guid("f4dd1a74-89f9-40f6-830c-a3ed1fd87000"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 19, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9470),
                            UserId = new Guid("62888c3c-bdbe-4f38-8ddd-4aad542b5343"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 20, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9470),
                            UserId = new Guid("b12707e1-0825-4f28-a393-baead7b33cbd"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 21, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9470),
                            UserId = new Guid("cb54e72f-3b57-4911-8247-f7479172598e"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 22, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9470),
                            UserId = new Guid("a61d4bd2-0b4c-4255-9643-a98a934f4fd9"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 23, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9470),
                            UserId = new Guid("aa2d1d4e-a1e9-4622-b7ec-2974ea4d7f88"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 24, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9480),
                            UserId = new Guid("65892d8c-be91-4bf0-afd4-753715e49bfe"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 25, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9480),
                            UserId = new Guid("cb30ba49-7982-46fb-95a7-35331c531752"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 26, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9480),
                            UserId = new Guid("7e3f0fa0-a9f6-4a7e-81cc-1af71768cf5a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 27, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9480),
                            UserId = new Guid("f6471fd8-80df-4ced-b8bd-83a69ae8db25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 28, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9480),
                            UserId = new Guid("f4dd1a74-89f9-40f6-830c-a3ed1fd87000"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 29, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9480),
                            UserId = new Guid("62888c3c-bdbe-4f38-8ddd-4aad542b5343"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 30, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9480),
                            UserId = new Guid("b12707e1-0825-4f28-a393-baead7b33cbd"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 31, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9480),
                            UserId = new Guid("cb54e72f-3b57-4911-8247-f7479172598e"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 1, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9480),
                            UserId = new Guid("a61d4bd2-0b4c-4255-9643-a98a934f4fd9"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 2, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9480),
                            UserId = new Guid("aa2d1d4e-a1e9-4622-b7ec-2974ea4d7f88"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 3, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9480),
                            UserId = new Guid("65892d8c-be91-4bf0-afd4-753715e49bfe"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 4, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9490),
                            UserId = new Guid("cb30ba49-7982-46fb-95a7-35331c531752"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 5, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9490),
                            UserId = new Guid("7e3f0fa0-a9f6-4a7e-81cc-1af71768cf5a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 6, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9490),
                            UserId = new Guid("f6471fd8-80df-4ced-b8bd-83a69ae8db25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 7, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9490),
                            UserId = new Guid("f4dd1a74-89f9-40f6-830c-a3ed1fd87000"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 8, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9490),
                            UserId = new Guid("62888c3c-bdbe-4f38-8ddd-4aad542b5343"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 9, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9490),
                            UserId = new Guid("b12707e1-0825-4f28-a393-baead7b33cbd"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 10, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9490),
                            UserId = new Guid("cb54e72f-3b57-4911-8247-f7479172598e"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 11, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9490),
                            UserId = new Guid("a61d4bd2-0b4c-4255-9643-a98a934f4fd9"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 12, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9490),
                            UserId = new Guid("aa2d1d4e-a1e9-4622-b7ec-2974ea4d7f88"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 13, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9490),
                            UserId = new Guid("65892d8c-be91-4bf0-afd4-753715e49bfe"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9500),
                            UserId = new Guid("cb30ba49-7982-46fb-95a7-35331c531752"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 15, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9500),
                            UserId = new Guid("7e3f0fa0-a9f6-4a7e-81cc-1af71768cf5a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 16, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9500),
                            UserId = new Guid("f6471fd8-80df-4ced-b8bd-83a69ae8db25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 17, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9500),
                            UserId = new Guid("f4dd1a74-89f9-40f6-830c-a3ed1fd87000"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 18, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9500),
                            UserId = new Guid("62888c3c-bdbe-4f38-8ddd-4aad542b5343"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 19, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9500),
                            UserId = new Guid("b12707e1-0825-4f28-a393-baead7b33cbd"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 20, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9500),
                            UserId = new Guid("cb54e72f-3b57-4911-8247-f7479172598e"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 21, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9500),
                            UserId = new Guid("a61d4bd2-0b4c-4255-9643-a98a934f4fd9"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 22, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9500),
                            UserId = new Guid("aa2d1d4e-a1e9-4622-b7ec-2974ea4d7f88"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 23, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9500),
                            UserId = new Guid("65892d8c-be91-4bf0-afd4-753715e49bfe"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 24, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9500),
                            UserId = new Guid("cb30ba49-7982-46fb-95a7-35331c531752"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 25, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9510),
                            UserId = new Guid("7e3f0fa0-a9f6-4a7e-81cc-1af71768cf5a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 26, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9510),
                            UserId = new Guid("f6471fd8-80df-4ced-b8bd-83a69ae8db25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 27, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9510),
                            UserId = new Guid("f4dd1a74-89f9-40f6-830c-a3ed1fd87000"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 28, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9510),
                            UserId = new Guid("62888c3c-bdbe-4f38-8ddd-4aad542b5343"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 29, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9510),
                            UserId = new Guid("b12707e1-0825-4f28-a393-baead7b33cbd"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 1, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9510),
                            UserId = new Guid("cb54e72f-3b57-4911-8247-f7479172598e"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 2, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9510),
                            UserId = new Guid("a61d4bd2-0b4c-4255-9643-a98a934f4fd9"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 3, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9510),
                            UserId = new Guid("aa2d1d4e-a1e9-4622-b7ec-2974ea4d7f88"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 4, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9510),
                            UserId = new Guid("65892d8c-be91-4bf0-afd4-753715e49bfe"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 5, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9510),
                            UserId = new Guid("cb30ba49-7982-46fb-95a7-35331c531752"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 6, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9510),
                            UserId = new Guid("7e3f0fa0-a9f6-4a7e-81cc-1af71768cf5a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 7, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9520),
                            UserId = new Guid("f6471fd8-80df-4ced-b8bd-83a69ae8db25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 8, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9520),
                            UserId = new Guid("f4dd1a74-89f9-40f6-830c-a3ed1fd87000"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 9, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9520),
                            UserId = new Guid("62888c3c-bdbe-4f38-8ddd-4aad542b5343"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 10, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9520),
                            UserId = new Guid("b12707e1-0825-4f28-a393-baead7b33cbd"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 11, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9520),
                            UserId = new Guid("cb54e72f-3b57-4911-8247-f7479172598e"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 12, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9520),
                            UserId = new Guid("a61d4bd2-0b4c-4255-9643-a98a934f4fd9"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 13, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(9520),
                            UserId = new Guid("aa2d1d4e-a1e9-4622-b7ec-2974ea4d7f88"),
                            Steps = 1000
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.SuperUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("password");

                    b.Property<string>("SuperRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("super_role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("SuperUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30e5af02-7e72-43f8-916e-405083629ba8"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 235, DateTimeKind.Local).AddTicks(3400),
                            Password = "$2a$05$JM/RNqZoQtw7a336B.Zj9uX2uBHf0rC3uuWq8uo5MdY0lBa.HSpe2",
                            SuperRole = "superAdmin",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 235, DateTimeKind.Local).AddTicks(3410),
                            Username = "superAdmin"
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65892d8c-be91-4bf0-afd4-753715e49bfe"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8810),
                            Identifier = "user0",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8840)
                        },
                        new
                        {
                            Id = new Guid("cb30ba49-7982-46fb-95a7-35331c531752"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8850),
                            Identifier = "user1",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8860)
                        },
                        new
                        {
                            Id = new Guid("7e3f0fa0-a9f6-4a7e-81cc-1af71768cf5a"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8860),
                            Identifier = "user2",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8860)
                        },
                        new
                        {
                            Id = new Guid("f6471fd8-80df-4ced-b8bd-83a69ae8db25"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8870),
                            Identifier = "user3",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8870)
                        },
                        new
                        {
                            Id = new Guid("f4dd1a74-89f9-40f6-830c-a3ed1fd87000"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8880),
                            Identifier = "user4",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8880)
                        },
                        new
                        {
                            Id = new Guid("62888c3c-bdbe-4f38-8ddd-4aad542b5343"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8890),
                            Identifier = "user5",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8890)
                        },
                        new
                        {
                            Id = new Guid("b12707e1-0825-4f28-a393-baead7b33cbd"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8890),
                            Identifier = "user6",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8900)
                        },
                        new
                        {
                            Id = new Guid("cb54e72f-3b57-4911-8247-f7479172598e"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8900),
                            Identifier = "user7",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8900)
                        },
                        new
                        {
                            Id = new Guid("a61d4bd2-0b4c-4255-9643-a98a934f4fd9"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8910),
                            Identifier = "user8",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8910)
                        },
                        new
                        {
                            Id = new Guid("aa2d1d4e-a1e9-4622-b7ec-2974ea4d7f88"),
                            CreatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8920),
                            Identifier = "user9",
                            UpdatedAt = new DateTime(2024, 3, 14, 13, 20, 31, 231, DateTimeKind.Local).AddTicks(8920)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Badge", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.User", null)
                        .WithMany("Badges")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.BadgesToUser", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarFitApi.Models.Database.User", "User")
                        .WithMany("BadgesToUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Challenge", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.Badge", "Badge")
                        .WithMany("Challenges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.DayOfWalk", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.User", "User")
                        .WithMany("DaysOfWalk")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Badge", b =>
                {
                    b.Navigation("Challenges");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.User", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("BadgesToUsers");

                    b.Navigation("DaysOfWalk");
                });
#pragma warning restore 612, 618
        }
    }
}
