// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StarFitApi.Models;

#nullable disable

namespace StarFitApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240313082529_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StarFitApi.Models.Database.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("IllustrationPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("illustration_path");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean")
                        .HasColumnName("published");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5ea13ed-fb6d-4991-bba2-f35d958852fb"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5520),
                            Description = "Content 0",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5520),
                            Title = "Article 0",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5530)
                        },
                        new
                        {
                            Id = new Guid("30aa28d4-cb79-48a5-8c2d-4c778f4bbabc"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5530),
                            Description = "Content 1",
                            IllustrationPath = "https://thumbs.dreamstime.com/b/bald-man-thumbs-up-26364248.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5530),
                            Title = "Article 1",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5540)
                        },
                        new
                        {
                            Id = new Guid("1deec16b-670a-4f87-80d7-6c79a061470e"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5540),
                            Description = "Content 2",
                            IllustrationPath = "https://previews.123rf.com/images/ambro/ambro1112/ambro111200418/11558816-businessman-with-thumbs-up.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5540),
                            Title = "Article 2",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5540)
                        },
                        new
                        {
                            Id = new Guid("8c11ea1f-d643-4cc3-989a-be2682a8d33b"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5550),
                            Description = "Content 3",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5550),
                            Title = "Article 3",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5550)
                        },
                        new
                        {
                            Id = new Guid("b1dbc66c-f222-450e-8f1c-0982432f5c25"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5560),
                            Description = "Content 4",
                            IllustrationPath = "https://thumbs.dreamstime.com/b/bald-man-thumbs-up-26364248.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5560),
                            Title = "Article 4",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5560)
                        },
                        new
                        {
                            Id = new Guid("53b3c661-6683-4098-80ec-11c98e8ff86f"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5570),
                            Description = "Content 5",
                            IllustrationPath = "https://previews.123rf.com/images/ambro/ambro1112/ambro111200418/11558816-businessman-with-thumbs-up.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5570),
                            Title = "Article 5",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5570)
                        },
                        new
                        {
                            Id = new Guid("bcd3cbea-9d1b-4230-b58a-855ce99e8ebc"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5580),
                            Description = "Content 6",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5580),
                            Title = "Article 6",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5580)
                        },
                        new
                        {
                            Id = new Guid("43cb147c-f3c4-447d-8de5-2b887200be95"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5590),
                            Description = "Content 7",
                            IllustrationPath = "https://thumbs.dreamstime.com/b/bald-man-thumbs-up-26364248.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5590),
                            Title = "Article 7",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5590)
                        },
                        new
                        {
                            Id = new Guid("3d44926f-60e6-48f0-ae08-92c8cf82bef2"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5600),
                            Description = "Content 8",
                            IllustrationPath = "https://previews.123rf.com/images/ambro/ambro1112/ambro111200418/11558816-businessman-with-thumbs-up.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5600),
                            Title = "Article 8",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5600)
                        },
                        new
                        {
                            Id = new Guid("6cc38a52-1ec6-4818-bf8d-919c3732b87d"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5610),
                            Description = "Content 9",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5610),
                            Title = "Article 9",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5610)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("icon_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11d90959-5e46-427b-a36d-7218bdb25558"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5240),
                            Description = "Content 0",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 0",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5240)
                        },
                        new
                        {
                            Id = new Guid("15edbc45-4d4d-4bec-bcb5-ad970229d5af"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5250),
                            Description = "Content 1",
                            IconPath = "https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM5LWltYWdlXzItbDBqOXFvd3IucG5n.png",
                            Title = "Badge 1",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5250)
                        },
                        new
                        {
                            Id = new Guid("2ffdaa12-c15a-4550-824e-5e8962b03605"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5260),
                            Description = "Content 2",
                            IconPath = "https://pngimg.com/uploads/cat/cat_PNG50447.png",
                            Title = "Badge 2",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5260)
                        },
                        new
                        {
                            Id = new Guid("240fac90-e939-44b7-aadd-ff1207f186a4"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5270),
                            Description = "Content 3",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 3",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5270)
                        },
                        new
                        {
                            Id = new Guid("e1e32864-72cf-435e-b803-9595b33088c9"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5270),
                            Description = "Content 4",
                            IconPath = "https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM5LWltYWdlXzItbDBqOXFvd3IucG5n.png",
                            Title = "Badge 4",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5270)
                        },
                        new
                        {
                            Id = new Guid("6fb5cf6c-ad79-4335-bd97-3f339c3d9f27"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5280),
                            Description = "Content 5",
                            IconPath = "https://pngimg.com/uploads/cat/cat_PNG50447.png",
                            Title = "Badge 5",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5280)
                        },
                        new
                        {
                            Id = new Guid("ec6d2ddd-056f-4ba3-a02d-eaad65398050"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5290),
                            Description = "Content 6",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 6",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5290)
                        },
                        new
                        {
                            Id = new Guid("3e267ec0-3971-4315-ab53-af72729e7c47"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5300),
                            Description = "Content 7",
                            IconPath = "https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM5LWltYWdlXzItbDBqOXFvd3IucG5n.png",
                            Title = "Badge 7",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5300)
                        },
                        new
                        {
                            Id = new Guid("8ab827e1-6f36-4948-93a2-07f0ac9a064b"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5310),
                            Description = "Content 8",
                            IconPath = "https://pngimg.com/uploads/cat/cat_PNG50447.png",
                            Title = "Badge 8",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5310)
                        },
                        new
                        {
                            Id = new Guid("e3835220-42cc-4044-8af7-42988d999ec7"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5310),
                            Description = "Content 9",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 9",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5320)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.BadgesToUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("ObtainedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("obtained_at");

                    b.HasKey("UserId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("BadgesToUser");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("420c3a0a-1f9c-433a-9e3f-8b6f9a904dc3"),
                            BadgeId = new Guid("11d90959-5e46-427b-a36d-7218bdb25558"),
                            ObtainedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5800)
                        },
                        new
                        {
                            UserId = new Guid("a3645c08-488a-442a-b231-0f3d082feb25"),
                            BadgeId = new Guid("15edbc45-4d4d-4bec-bcb5-ad970229d5af"),
                            ObtainedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5800)
                        },
                        new
                        {
                            UserId = new Guid("bffa7c13-f94d-4f8d-bf8b-0c42d083c141"),
                            BadgeId = new Guid("2ffdaa12-c15a-4550-824e-5e8962b03605"),
                            ObtainedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5800)
                        },
                        new
                        {
                            UserId = new Guid("54cc6ef5-ba2b-439e-95b1-497097f90fae"),
                            BadgeId = new Guid("240fac90-e939-44b7-aadd-ff1207f186a4"),
                            ObtainedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5800)
                        },
                        new
                        {
                            UserId = new Guid("67a4cd57-52a8-48b8-86e6-8908d68891b1"),
                            BadgeId = new Guid("e1e32864-72cf-435e-b803-9595b33088c9"),
                            ObtainedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5800)
                        },
                        new
                        {
                            UserId = new Guid("c005dc28-a96a-42d1-8d90-863ad782aef7"),
                            BadgeId = new Guid("6fb5cf6c-ad79-4335-bd97-3f339c3d9f27"),
                            ObtainedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5800)
                        },
                        new
                        {
                            UserId = new Guid("a1260164-dd80-461c-8cae-b96272ee3176"),
                            BadgeId = new Guid("ec6d2ddd-056f-4ba3-a02d-eaad65398050"),
                            ObtainedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5800)
                        },
                        new
                        {
                            UserId = new Guid("9b0d0861-9076-4c54-8139-3f493889e17b"),
                            BadgeId = new Guid("3e267ec0-3971-4315-ab53-af72729e7c47"),
                            ObtainedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5800)
                        },
                        new
                        {
                            UserId = new Guid("72d0e2db-cf56-47fd-bf2d-96b4e2fa63df"),
                            BadgeId = new Guid("8ab827e1-6f36-4948-93a2-07f0ac9a064b"),
                            ObtainedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5810)
                        },
                        new
                        {
                            UserId = new Guid("b94479bd-7194-4635-9cf7-b54404822084"),
                            BadgeId = new Guid("e3835220-42cc-4044-8af7-42988d999ec7"),
                            ObtainedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5810)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_global");

                    b.Property<int>("Objective")
                        .HasColumnType("integer")
                        .HasColumnName("objective");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.ToTable("Challenges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5759d211-2023-4e84-8f74-7f8b365616ee"),
                            BadgeId = new Guid("11d90959-5e46-427b-a36d-7218bdb25558"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5370),
                            Description = "Content 0",
                            EndDate = new DateTime(2024, 4, 12, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5360),
                            IsGlobal = true,
                            Objective = 18349,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5360),
                            Title = "Challenge 0",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5370)
                        },
                        new
                        {
                            Id = new Guid("74b53410-644a-427f-bcc7-ce0a7289c70e"),
                            BadgeId = new Guid("15edbc45-4d4d-4bec-bcb5-ad970229d5af"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5390),
                            Description = "Content 1",
                            EndDate = new DateTime(2024, 4, 12, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5390),
                            IsGlobal = false,
                            Objective = 73916,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5390),
                            Title = "Challenge 1",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5390)
                        },
                        new
                        {
                            Id = new Guid("771d5aee-21dc-4ce9-9424-a12b7179b1b3"),
                            BadgeId = new Guid("2ffdaa12-c15a-4550-824e-5e8962b03605"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5400),
                            Description = "Content 2",
                            EndDate = new DateTime(2024, 4, 12, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5400),
                            IsGlobal = true,
                            Objective = 57954,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5400),
                            Title = "Challenge 2",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5400)
                        },
                        new
                        {
                            Id = new Guid("7f36a21e-002f-493a-a6d6-9f5389cf192d"),
                            BadgeId = new Guid("240fac90-e939-44b7-aadd-ff1207f186a4"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5410),
                            Description = "Content 3",
                            EndDate = new DateTime(2024, 4, 12, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5410),
                            IsGlobal = false,
                            Objective = 59999,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5410),
                            Title = "Challenge 3",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5410)
                        },
                        new
                        {
                            Id = new Guid("7e5525d2-46cb-4cb9-b331-30c181d99ae2"),
                            BadgeId = new Guid("e1e32864-72cf-435e-b803-9595b33088c9"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5420),
                            Description = "Content 4",
                            EndDate = new DateTime(2024, 4, 12, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5420),
                            IsGlobal = true,
                            Objective = 38121,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5420),
                            Title = "Challenge 4",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5430)
                        },
                        new
                        {
                            Id = new Guid("6d5464f5-c544-4807-b4e3-53b4f97a23d8"),
                            BadgeId = new Guid("6fb5cf6c-ad79-4335-bd97-3f339c3d9f27"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5440),
                            Description = "Content 5",
                            EndDate = new DateTime(2024, 4, 12, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5440),
                            IsGlobal = false,
                            Objective = 50939,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5440),
                            Title = "Challenge 5",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5440)
                        },
                        new
                        {
                            Id = new Guid("8a1da8a7-da79-49bc-837d-742d1dca08dc"),
                            BadgeId = new Guid("ec6d2ddd-056f-4ba3-a02d-eaad65398050"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5450),
                            Description = "Content 6",
                            EndDate = new DateTime(2024, 4, 12, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5450),
                            IsGlobal = true,
                            Objective = 85250,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5450),
                            Title = "Challenge 6",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5450)
                        },
                        new
                        {
                            Id = new Guid("c73e5b91-36da-41d5-aeee-06f0fe241f7c"),
                            BadgeId = new Guid("3e267ec0-3971-4315-ab53-af72729e7c47"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5460),
                            Description = "Content 7",
                            EndDate = new DateTime(2024, 4, 12, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5460),
                            IsGlobal = false,
                            Objective = 71615,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5460),
                            Title = "Challenge 7",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5460)
                        },
                        new
                        {
                            Id = new Guid("c5f10631-3bf3-417d-a939-b414637d428c"),
                            BadgeId = new Guid("8ab827e1-6f36-4948-93a2-07f0ac9a064b"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5470),
                            Description = "Content 8",
                            EndDate = new DateTime(2024, 4, 12, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5470),
                            IsGlobal = true,
                            Objective = 23401,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5470),
                            Title = "Challenge 8",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5470)
                        },
                        new
                        {
                            Id = new Guid("0c65cab9-72e2-4143-b707-2b4b4272a0d0"),
                            BadgeId = new Guid("e3835220-42cc-4044-8af7-42988d999ec7"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5490),
                            Description = "Content 9",
                            EndDate = new DateTime(2024, 4, 12, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5490),
                            IsGlobal = false,
                            Objective = 8120,
                            StartDate = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5480),
                            Title = "Challenge 9",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5490)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.DayOfWalk", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Steps")
                        .HasColumnType("integer")
                        .HasColumnName("steps");

                    b.HasKey("Date", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("DayOfWalk");

                    b.HasData(
                        new
                        {
                            Date = new DateTime(2023, 12, 4, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5630),
                            UserId = new Guid("420c3a0a-1f9c-433a-9e3f-8b6f9a904dc3"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 5, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5630),
                            UserId = new Guid("a3645c08-488a-442a-b231-0f3d082feb25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 6, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5630),
                            UserId = new Guid("bffa7c13-f94d-4f8d-bf8b-0c42d083c141"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 7, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5630),
                            UserId = new Guid("54cc6ef5-ba2b-439e-95b1-497097f90fae"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 8, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5630),
                            UserId = new Guid("67a4cd57-52a8-48b8-86e6-8908d68891b1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 9, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5640),
                            UserId = new Guid("c005dc28-a96a-42d1-8d90-863ad782aef7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 10, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5640),
                            UserId = new Guid("a1260164-dd80-461c-8cae-b96272ee3176"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 11, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5640),
                            UserId = new Guid("9b0d0861-9076-4c54-8139-3f493889e17b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 12, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5640),
                            UserId = new Guid("72d0e2db-cf56-47fd-bf2d-96b4e2fa63df"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5640),
                            UserId = new Guid("b94479bd-7194-4635-9cf7-b54404822084"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 14, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5640),
                            UserId = new Guid("420c3a0a-1f9c-433a-9e3f-8b6f9a904dc3"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 15, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5640),
                            UserId = new Guid("a3645c08-488a-442a-b231-0f3d082feb25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 16, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5640),
                            UserId = new Guid("bffa7c13-f94d-4f8d-bf8b-0c42d083c141"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 17, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5640),
                            UserId = new Guid("54cc6ef5-ba2b-439e-95b1-497097f90fae"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 18, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5650),
                            UserId = new Guid("67a4cd57-52a8-48b8-86e6-8908d68891b1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 19, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5650),
                            UserId = new Guid("c005dc28-a96a-42d1-8d90-863ad782aef7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 20, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5650),
                            UserId = new Guid("a1260164-dd80-461c-8cae-b96272ee3176"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 21, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5650),
                            UserId = new Guid("9b0d0861-9076-4c54-8139-3f493889e17b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 22, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5650),
                            UserId = new Guid("72d0e2db-cf56-47fd-bf2d-96b4e2fa63df"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 23, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5650),
                            UserId = new Guid("b94479bd-7194-4635-9cf7-b54404822084"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 24, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5650),
                            UserId = new Guid("420c3a0a-1f9c-433a-9e3f-8b6f9a904dc3"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 25, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5650),
                            UserId = new Guid("a3645c08-488a-442a-b231-0f3d082feb25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 26, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5650),
                            UserId = new Guid("bffa7c13-f94d-4f8d-bf8b-0c42d083c141"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 27, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5650),
                            UserId = new Guid("54cc6ef5-ba2b-439e-95b1-497097f90fae"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 28, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5660),
                            UserId = new Guid("67a4cd57-52a8-48b8-86e6-8908d68891b1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 29, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5660),
                            UserId = new Guid("c005dc28-a96a-42d1-8d90-863ad782aef7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 30, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5660),
                            UserId = new Guid("a1260164-dd80-461c-8cae-b96272ee3176"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 31, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5660),
                            UserId = new Guid("9b0d0861-9076-4c54-8139-3f493889e17b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 1, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5660),
                            UserId = new Guid("72d0e2db-cf56-47fd-bf2d-96b4e2fa63df"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 2, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5660),
                            UserId = new Guid("b94479bd-7194-4635-9cf7-b54404822084"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 3, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5660),
                            UserId = new Guid("420c3a0a-1f9c-433a-9e3f-8b6f9a904dc3"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 4, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5660),
                            UserId = new Guid("a3645c08-488a-442a-b231-0f3d082feb25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 5, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5660),
                            UserId = new Guid("bffa7c13-f94d-4f8d-bf8b-0c42d083c141"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 6, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5660),
                            UserId = new Guid("54cc6ef5-ba2b-439e-95b1-497097f90fae"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 7, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5670),
                            UserId = new Guid("67a4cd57-52a8-48b8-86e6-8908d68891b1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 8, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5670),
                            UserId = new Guid("c005dc28-a96a-42d1-8d90-863ad782aef7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 9, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5670),
                            UserId = new Guid("a1260164-dd80-461c-8cae-b96272ee3176"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 10, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5670),
                            UserId = new Guid("9b0d0861-9076-4c54-8139-3f493889e17b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 11, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5670),
                            UserId = new Guid("72d0e2db-cf56-47fd-bf2d-96b4e2fa63df"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 12, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5670),
                            UserId = new Guid("b94479bd-7194-4635-9cf7-b54404822084"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5670),
                            UserId = new Guid("420c3a0a-1f9c-433a-9e3f-8b6f9a904dc3"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 14, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5670),
                            UserId = new Guid("a3645c08-488a-442a-b231-0f3d082feb25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 15, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5670),
                            UserId = new Guid("bffa7c13-f94d-4f8d-bf8b-0c42d083c141"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 16, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5670),
                            UserId = new Guid("54cc6ef5-ba2b-439e-95b1-497097f90fae"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 17, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5680),
                            UserId = new Guid("67a4cd57-52a8-48b8-86e6-8908d68891b1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 18, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5680),
                            UserId = new Guid("c005dc28-a96a-42d1-8d90-863ad782aef7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 19, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5680),
                            UserId = new Guid("a1260164-dd80-461c-8cae-b96272ee3176"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 20, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5680),
                            UserId = new Guid("9b0d0861-9076-4c54-8139-3f493889e17b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 21, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5680),
                            UserId = new Guid("72d0e2db-cf56-47fd-bf2d-96b4e2fa63df"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 22, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5680),
                            UserId = new Guid("b94479bd-7194-4635-9cf7-b54404822084"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 23, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5680),
                            UserId = new Guid("420c3a0a-1f9c-433a-9e3f-8b6f9a904dc3"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 24, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5680),
                            UserId = new Guid("a3645c08-488a-442a-b231-0f3d082feb25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 25, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5680),
                            UserId = new Guid("bffa7c13-f94d-4f8d-bf8b-0c42d083c141"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 26, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5680),
                            UserId = new Guid("54cc6ef5-ba2b-439e-95b1-497097f90fae"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 27, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5680),
                            UserId = new Guid("67a4cd57-52a8-48b8-86e6-8908d68891b1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 28, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5690),
                            UserId = new Guid("c005dc28-a96a-42d1-8d90-863ad782aef7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 29, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5690),
                            UserId = new Guid("a1260164-dd80-461c-8cae-b96272ee3176"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 30, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5690),
                            UserId = new Guid("9b0d0861-9076-4c54-8139-3f493889e17b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 31, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5690),
                            UserId = new Guid("72d0e2db-cf56-47fd-bf2d-96b4e2fa63df"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 1, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5690),
                            UserId = new Guid("b94479bd-7194-4635-9cf7-b54404822084"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 2, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5690),
                            UserId = new Guid("420c3a0a-1f9c-433a-9e3f-8b6f9a904dc3"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 3, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5690),
                            UserId = new Guid("a3645c08-488a-442a-b231-0f3d082feb25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 4, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5690),
                            UserId = new Guid("bffa7c13-f94d-4f8d-bf8b-0c42d083c141"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 5, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5690),
                            UserId = new Guid("54cc6ef5-ba2b-439e-95b1-497097f90fae"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 6, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5690),
                            UserId = new Guid("67a4cd57-52a8-48b8-86e6-8908d68891b1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 7, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5700),
                            UserId = new Guid("c005dc28-a96a-42d1-8d90-863ad782aef7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 8, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5700),
                            UserId = new Guid("a1260164-dd80-461c-8cae-b96272ee3176"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 9, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5700),
                            UserId = new Guid("9b0d0861-9076-4c54-8139-3f493889e17b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 10, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5700),
                            UserId = new Guid("72d0e2db-cf56-47fd-bf2d-96b4e2fa63df"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 11, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5700),
                            UserId = new Guid("b94479bd-7194-4635-9cf7-b54404822084"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 12, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5700),
                            UserId = new Guid("420c3a0a-1f9c-433a-9e3f-8b6f9a904dc3"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5700),
                            UserId = new Guid("a3645c08-488a-442a-b231-0f3d082feb25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 14, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5700),
                            UserId = new Guid("bffa7c13-f94d-4f8d-bf8b-0c42d083c141"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 15, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5700),
                            UserId = new Guid("54cc6ef5-ba2b-439e-95b1-497097f90fae"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 16, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5700),
                            UserId = new Guid("67a4cd57-52a8-48b8-86e6-8908d68891b1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 17, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5710),
                            UserId = new Guid("c005dc28-a96a-42d1-8d90-863ad782aef7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 18, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5710),
                            UserId = new Guid("a1260164-dd80-461c-8cae-b96272ee3176"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 19, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5710),
                            UserId = new Guid("9b0d0861-9076-4c54-8139-3f493889e17b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 20, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5710),
                            UserId = new Guid("72d0e2db-cf56-47fd-bf2d-96b4e2fa63df"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 21, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5710),
                            UserId = new Guid("b94479bd-7194-4635-9cf7-b54404822084"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 22, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5710),
                            UserId = new Guid("420c3a0a-1f9c-433a-9e3f-8b6f9a904dc3"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 23, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5710),
                            UserId = new Guid("a3645c08-488a-442a-b231-0f3d082feb25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 24, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5710),
                            UserId = new Guid("bffa7c13-f94d-4f8d-bf8b-0c42d083c141"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 25, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5710),
                            UserId = new Guid("54cc6ef5-ba2b-439e-95b1-497097f90fae"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 26, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5710),
                            UserId = new Guid("67a4cd57-52a8-48b8-86e6-8908d68891b1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 27, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5710),
                            UserId = new Guid("c005dc28-a96a-42d1-8d90-863ad782aef7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 28, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5730),
                            UserId = new Guid("a1260164-dd80-461c-8cae-b96272ee3176"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 29, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5730),
                            UserId = new Guid("9b0d0861-9076-4c54-8139-3f493889e17b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 1, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5730),
                            UserId = new Guid("72d0e2db-cf56-47fd-bf2d-96b4e2fa63df"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 2, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5740),
                            UserId = new Guid("b94479bd-7194-4635-9cf7-b54404822084"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 3, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5740),
                            UserId = new Guid("420c3a0a-1f9c-433a-9e3f-8b6f9a904dc3"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 4, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5740),
                            UserId = new Guid("a3645c08-488a-442a-b231-0f3d082feb25"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 5, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5740),
                            UserId = new Guid("bffa7c13-f94d-4f8d-bf8b-0c42d083c141"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 6, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5740),
                            UserId = new Guid("54cc6ef5-ba2b-439e-95b1-497097f90fae"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 7, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5740),
                            UserId = new Guid("67a4cd57-52a8-48b8-86e6-8908d68891b1"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 8, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5740),
                            UserId = new Guid("c005dc28-a96a-42d1-8d90-863ad782aef7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 9, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5740),
                            UserId = new Guid("a1260164-dd80-461c-8cae-b96272ee3176"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 10, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5740),
                            UserId = new Guid("9b0d0861-9076-4c54-8139-3f493889e17b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 11, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5740),
                            UserId = new Guid("72d0e2db-cf56-47fd-bf2d-96b4e2fa63df"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 12, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5740),
                            UserId = new Guid("b94479bd-7194-4635-9cf7-b54404822084"),
                            Steps = 1000
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.SuperUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("password");

                    b.Property<string>("SuperRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("super_role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("SuperUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0729612a-9693-4d6d-b179-b7d8c7544750"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 899, DateTimeKind.Local).AddTicks(9290),
                            Password = "$2a$05$WDZbqAg1VHlZa.uBz33k.OrMsg79Nn80.MWvZLEAA9WCrthpUoStO",
                            SuperRole = "superAdmin",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 899, DateTimeKind.Local).AddTicks(9290),
                            Username = "superAdmin"
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("420c3a0a-1f9c-433a-9e3f-8b6f9a904dc3"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5010),
                            Identifier = "user0",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5050)
                        },
                        new
                        {
                            Id = new Guid("a3645c08-488a-442a-b231-0f3d082feb25"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5060),
                            Identifier = "user1",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5060)
                        },
                        new
                        {
                            Id = new Guid("bffa7c13-f94d-4f8d-bf8b-0c42d083c141"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5070),
                            Identifier = "user2",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5070)
                        },
                        new
                        {
                            Id = new Guid("54cc6ef5-ba2b-439e-95b1-497097f90fae"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5080),
                            Identifier = "user3",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5080)
                        },
                        new
                        {
                            Id = new Guid("67a4cd57-52a8-48b8-86e6-8908d68891b1"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5090),
                            Identifier = "user4",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5090)
                        },
                        new
                        {
                            Id = new Guid("c005dc28-a96a-42d1-8d90-863ad782aef7"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5100),
                            Identifier = "user5",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5100)
                        },
                        new
                        {
                            Id = new Guid("a1260164-dd80-461c-8cae-b96272ee3176"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5100),
                            Identifier = "user6",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5100)
                        },
                        new
                        {
                            Id = new Guid("9b0d0861-9076-4c54-8139-3f493889e17b"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5110),
                            Identifier = "user7",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5110)
                        },
                        new
                        {
                            Id = new Guid("72d0e2db-cf56-47fd-bf2d-96b4e2fa63df"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5120),
                            Identifier = "user8",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5120)
                        },
                        new
                        {
                            Id = new Guid("b94479bd-7194-4635-9cf7-b54404822084"),
                            CreatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5150),
                            Identifier = "user9",
                            UpdatedAt = new DateTime(2024, 3, 13, 9, 25, 29, 896, DateTimeKind.Local).AddTicks(5150)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Badge", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.User", null)
                        .WithMany("Badges")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.BadgesToUser", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarFitApi.Models.Database.User", "User")
                        .WithMany("BadgesToUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Challenge", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.Badge", "Badge")
                        .WithMany("Challenges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.DayOfWalk", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.User", "User")
                        .WithMany("DaysOfWalk")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Badge", b =>
                {
                    b.Navigation("Challenges");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.User", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("BadgesToUsers");

                    b.Navigation("DaysOfWalk");
                });
#pragma warning restore 612, 618
        }
    }
}
