// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StarFitApi.Models;

#nullable disable

namespace StarFitApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240312203337_AddedSuperUserTable")]
    partial class AddedSuperUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StarFitApi.Models.Database.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("IllustrationPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("illustration_path");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean")
                        .HasColumnName("published");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5648dfee-e174-4798-8862-1b321d9704a7"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6530),
                            Description = "Content 0",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6530),
                            Title = "Article 0",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6530)
                        },
                        new
                        {
                            Id = new Guid("4cf8d8b9-0628-467b-9285-34a14a47986b"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6540),
                            Description = "Content 1",
                            IllustrationPath = "https://thumbs.dreamstime.com/b/bald-man-thumbs-up-26364248.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6540),
                            Title = "Article 1",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6540)
                        },
                        new
                        {
                            Id = new Guid("2766f6a8-e509-410d-8915-074441d6af04"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6550),
                            Description = "Content 2",
                            IllustrationPath = "https://previews.123rf.com/images/ambro/ambro1112/ambro111200418/11558816-businessman-with-thumbs-up.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6550),
                            Title = "Article 2",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6550)
                        },
                        new
                        {
                            Id = new Guid("7c3e145e-8d32-424e-980c-9555ff7eceac"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6560),
                            Description = "Content 3",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6560),
                            Title = "Article 3",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6560)
                        },
                        new
                        {
                            Id = new Guid("8e41c9f9-f11c-4e07-b5b0-7d99b6c682f5"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6570),
                            Description = "Content 4",
                            IllustrationPath = "https://thumbs.dreamstime.com/b/bald-man-thumbs-up-26364248.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6570),
                            Title = "Article 4",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6570)
                        },
                        new
                        {
                            Id = new Guid("328a8d1f-0e82-4029-a1f1-b7acd84be780"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6580),
                            Description = "Content 5",
                            IllustrationPath = "https://previews.123rf.com/images/ambro/ambro1112/ambro111200418/11558816-businessman-with-thumbs-up.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6580),
                            Title = "Article 5",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6580)
                        },
                        new
                        {
                            Id = new Guid("ea864f4f-e0f1-4c1c-b96a-256488f28fe3"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6590),
                            Description = "Content 6",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6590),
                            Title = "Article 6",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6590)
                        },
                        new
                        {
                            Id = new Guid("e23be446-a112-472a-97ea-1009c2fb98bf"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6600),
                            Description = "Content 7",
                            IllustrationPath = "https://thumbs.dreamstime.com/b/bald-man-thumbs-up-26364248.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6600),
                            Title = "Article 7",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6600)
                        },
                        new
                        {
                            Id = new Guid("63cb7e99-4e60-4e6d-b00a-7b179eed7675"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6610),
                            Description = "Content 8",
                            IllustrationPath = "https://previews.123rf.com/images/ambro/ambro1112/ambro111200418/11558816-businessman-with-thumbs-up.jpg",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6610),
                            Title = "Article 8",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6610)
                        },
                        new
                        {
                            Id = new Guid("bc204755-d233-4951-83d6-1af77b706467"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6620),
                            Description = "Content 9",
                            IllustrationPath = "https://media.istockphoto.com/id/182060276/photo/casual-man-gesturing-thumbs-up-isolated.jpg?s=612x612&w=0&k=20&c=YYCr9xSywy1pxJRskxEPYuM8T0PYTX3ylFG0C1pXyd4=",
                            Published = true,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6620),
                            Title = "Article 9",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6620)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("icon_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44cacbd7-ed31-4116-a5fa-f750020e0b1e"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6230),
                            Description = "Content 0",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 0",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6230)
                        },
                        new
                        {
                            Id = new Guid("22b8a2fc-62b9-49b6-8926-91a297ae2d00"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6240),
                            Description = "Content 1",
                            IconPath = "https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM5LWltYWdlXzItbDBqOXFvd3IucG5n.png",
                            Title = "Badge 1",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6240)
                        },
                        new
                        {
                            Id = new Guid("ebeb732c-d0f0-47ae-b1ce-b572403c26b7"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6250),
                            Description = "Content 2",
                            IconPath = "https://pngimg.com/uploads/cat/cat_PNG50447.png",
                            Title = "Badge 2",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6250)
                        },
                        new
                        {
                            Id = new Guid("d0046aa4-dbec-47ba-9e28-2ffcae66fbfb"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6260),
                            Description = "Content 3",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 3",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6260)
                        },
                        new
                        {
                            Id = new Guid("2ed7d868-efd2-47d8-8375-eead449bb1ea"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6260),
                            Description = "Content 4",
                            IconPath = "https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM5LWltYWdlXzItbDBqOXFvd3IucG5n.png",
                            Title = "Badge 4",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6270)
                        },
                        new
                        {
                            Id = new Guid("879a4b23-d8a8-4d58-87c3-54a08c6f5bf3"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6270),
                            Description = "Content 5",
                            IconPath = "https://pngimg.com/uploads/cat/cat_PNG50447.png",
                            Title = "Badge 5",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6270)
                        },
                        new
                        {
                            Id = new Guid("e8a4ab9d-3eae-4dd3-8900-ee2debbf90f1"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6280),
                            Description = "Content 6",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 6",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6280)
                        },
                        new
                        {
                            Id = new Guid("36f7239e-502d-413b-847f-2ac07362f70c"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6290),
                            Description = "Content 7",
                            IconPath = "https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM5LWltYWdlXzItbDBqOXFvd3IucG5n.png",
                            Title = "Badge 7",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6290)
                        },
                        new
                        {
                            Id = new Guid("21788ab5-8329-4339-9e56-7b709772f6ea"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6300),
                            Description = "Content 8",
                            IconPath = "https://pngimg.com/uploads/cat/cat_PNG50447.png",
                            Title = "Badge 8",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6300)
                        },
                        new
                        {
                            Id = new Guid("08823ad9-9907-48a9-8ba0-b147e4d55d5c"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6310),
                            Description = "Content 9",
                            IconPath = "https://png.pngtree.com/png-vector/20201229/ourmid/pngtree-a-squatting-tabby-cat-png-image_2664942.jpg",
                            Title = "Badge 9",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6310)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.BadgesToUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("ObtainedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("obtained_at");

                    b.HasKey("UserId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("BadgesToUser");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("368c6dee-0c79-4673-b178-bf23125a7d0a"),
                            BadgeId = new Guid("44cacbd7-ed31-4116-a5fa-f750020e0b1e"),
                            ObtainedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6780)
                        },
                        new
                        {
                            UserId = new Guid("e61d255f-8b80-4e08-9c08-dbab8df42f17"),
                            BadgeId = new Guid("22b8a2fc-62b9-49b6-8926-91a297ae2d00"),
                            ObtainedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6790)
                        },
                        new
                        {
                            UserId = new Guid("ad4f12f8-6280-47a1-9e8f-54e97b84e792"),
                            BadgeId = new Guid("ebeb732c-d0f0-47ae-b1ce-b572403c26b7"),
                            ObtainedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6790)
                        },
                        new
                        {
                            UserId = new Guid("6718d752-9569-4126-90b2-7e00f5990b0a"),
                            BadgeId = new Guid("d0046aa4-dbec-47ba-9e28-2ffcae66fbfb"),
                            ObtainedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6790)
                        },
                        new
                        {
                            UserId = new Guid("51485224-7236-4cdf-a155-76f66c3d1795"),
                            BadgeId = new Guid("2ed7d868-efd2-47d8-8375-eead449bb1ea"),
                            ObtainedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6790)
                        },
                        new
                        {
                            UserId = new Guid("98296d73-6a0c-4da9-8362-6fa8dcfb5de7"),
                            BadgeId = new Guid("879a4b23-d8a8-4d58-87c3-54a08c6f5bf3"),
                            ObtainedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6790)
                        },
                        new
                        {
                            UserId = new Guid("5099b530-3bf7-47ba-b894-8291236a0198"),
                            BadgeId = new Guid("e8a4ab9d-3eae-4dd3-8900-ee2debbf90f1"),
                            ObtainedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6790)
                        },
                        new
                        {
                            UserId = new Guid("7956c394-e9c5-4b9c-904f-954c459bad02"),
                            BadgeId = new Guid("36f7239e-502d-413b-847f-2ac07362f70c"),
                            ObtainedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6790)
                        },
                        new
                        {
                            UserId = new Guid("c35e44b0-57ef-456f-8d7a-d0a12f9df13b"),
                            BadgeId = new Guid("21788ab5-8329-4339-9e56-7b709772f6ea"),
                            ObtainedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6790)
                        },
                        new
                        {
                            UserId = new Guid("ac6b08e1-53e3-4364-a6af-0a7ecc299154"),
                            BadgeId = new Guid("08823ad9-9907-48a9-8ba0-b147e4d55d5c"),
                            ObtainedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6810)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_global");

                    b.Property<int>("Objective")
                        .HasColumnType("integer")
                        .HasColumnName("objective");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.ToTable("Challenges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c21ea06b-ddd6-406f-aba0-0054224867f1"),
                            BadgeId = new Guid("44cacbd7-ed31-4116-a5fa-f750020e0b1e"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6360),
                            Description = "Content 0",
                            EndDate = new DateTime(2024, 4, 11, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6360),
                            IsGlobal = true,
                            Objective = 90177,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6350),
                            Title = "Challenge 0",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6360)
                        },
                        new
                        {
                            Id = new Guid("083b6ace-924e-43bd-90e2-cc9ea1283a2f"),
                            BadgeId = new Guid("22b8a2fc-62b9-49b6-8926-91a297ae2d00"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6380),
                            Description = "Content 1",
                            EndDate = new DateTime(2024, 4, 11, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6380),
                            IsGlobal = false,
                            Objective = 9359,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6380),
                            Title = "Challenge 1",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6380)
                        },
                        new
                        {
                            Id = new Guid("723f1c4b-5c9f-4c14-8b3a-8f94a2551131"),
                            BadgeId = new Guid("ebeb732c-d0f0-47ae-b1ce-b572403c26b7"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6390),
                            Description = "Content 2",
                            EndDate = new DateTime(2024, 4, 11, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6390),
                            IsGlobal = true,
                            Objective = 84028,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6390),
                            Title = "Challenge 2",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6390)
                        },
                        new
                        {
                            Id = new Guid("82c02a0c-6101-43bf-9e0f-c8b76f47cc4c"),
                            BadgeId = new Guid("d0046aa4-dbec-47ba-9e28-2ffcae66fbfb"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6420),
                            Description = "Content 3",
                            EndDate = new DateTime(2024, 4, 11, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6420),
                            IsGlobal = false,
                            Objective = 61343,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6420),
                            Title = "Challenge 3",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6420)
                        },
                        new
                        {
                            Id = new Guid("268fb02f-6d22-42a4-9581-a20ea9c42228"),
                            BadgeId = new Guid("2ed7d868-efd2-47d8-8375-eead449bb1ea"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6440),
                            Description = "Content 4",
                            EndDate = new DateTime(2024, 4, 11, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6440),
                            IsGlobal = true,
                            Objective = 23502,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6430),
                            Title = "Challenge 4",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6440)
                        },
                        new
                        {
                            Id = new Guid("f46ec2c0-ac8c-4561-a118-79d7c7a35524"),
                            BadgeId = new Guid("879a4b23-d8a8-4d58-87c3-54a08c6f5bf3"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6450),
                            Description = "Content 5",
                            EndDate = new DateTime(2024, 4, 11, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6450),
                            IsGlobal = false,
                            Objective = 77579,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6450),
                            Title = "Challenge 5",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6450)
                        },
                        new
                        {
                            Id = new Guid("171a179f-1a6c-41b5-91e7-fe3991cd8bf0"),
                            BadgeId = new Guid("e8a4ab9d-3eae-4dd3-8900-ee2debbf90f1"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6460),
                            Description = "Content 6",
                            EndDate = new DateTime(2024, 4, 11, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6460),
                            IsGlobal = true,
                            Objective = 16050,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6460),
                            Title = "Challenge 6",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6460)
                        },
                        new
                        {
                            Id = new Guid("b8f8f98e-b975-4bef-8627-be31b31b404e"),
                            BadgeId = new Guid("36f7239e-502d-413b-847f-2ac07362f70c"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6470),
                            Description = "Content 7",
                            EndDate = new DateTime(2024, 4, 11, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6470),
                            IsGlobal = false,
                            Objective = 21578,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6470),
                            Title = "Challenge 7",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6470)
                        },
                        new
                        {
                            Id = new Guid("153cdeda-6f23-44cd-9d7a-b2d28031de5d"),
                            BadgeId = new Guid("21788ab5-8329-4339-9e56-7b709772f6ea"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6490),
                            Description = "Content 8",
                            EndDate = new DateTime(2024, 4, 11, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6490),
                            IsGlobal = true,
                            Objective = 92495,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6490),
                            Title = "Challenge 8",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6490)
                        },
                        new
                        {
                            Id = new Guid("2a92a319-5e77-4deb-99eb-3cdbc83bb03d"),
                            BadgeId = new Guid("08823ad9-9907-48a9-8ba0-b147e4d55d5c"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6500),
                            Description = "Content 9",
                            EndDate = new DateTime(2024, 4, 11, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6500),
                            IsGlobal = false,
                            Objective = 6993,
                            StartDate = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6500),
                            Title = "Challenge 9",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6500)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.DayOfWalk", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Steps")
                        .HasColumnType("integer")
                        .HasColumnName("steps");

                    b.HasKey("Date", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("DayOfWalk");

                    b.HasData(
                        new
                        {
                            Date = new DateTime(2023, 12, 3, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6640),
                            UserId = new Guid("368c6dee-0c79-4673-b178-bf23125a7d0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 4, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6640),
                            UserId = new Guid("e61d255f-8b80-4e08-9c08-dbab8df42f17"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 5, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6640),
                            UserId = new Guid("ad4f12f8-6280-47a1-9e8f-54e97b84e792"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 6, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6640),
                            UserId = new Guid("6718d752-9569-4126-90b2-7e00f5990b0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 7, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6640),
                            UserId = new Guid("51485224-7236-4cdf-a155-76f66c3d1795"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 8, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6640),
                            UserId = new Guid("98296d73-6a0c-4da9-8362-6fa8dcfb5de7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 9, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6650),
                            UserId = new Guid("5099b530-3bf7-47ba-b894-8291236a0198"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 10, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6650),
                            UserId = new Guid("7956c394-e9c5-4b9c-904f-954c459bad02"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 11, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6650),
                            UserId = new Guid("c35e44b0-57ef-456f-8d7a-d0a12f9df13b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6650),
                            UserId = new Guid("ac6b08e1-53e3-4364-a6af-0a7ecc299154"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 13, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6650),
                            UserId = new Guid("368c6dee-0c79-4673-b178-bf23125a7d0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 14, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6650),
                            UserId = new Guid("e61d255f-8b80-4e08-9c08-dbab8df42f17"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 15, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6650),
                            UserId = new Guid("ad4f12f8-6280-47a1-9e8f-54e97b84e792"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 16, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6650),
                            UserId = new Guid("6718d752-9569-4126-90b2-7e00f5990b0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 17, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6650),
                            UserId = new Guid("51485224-7236-4cdf-a155-76f66c3d1795"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 18, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6660),
                            UserId = new Guid("98296d73-6a0c-4da9-8362-6fa8dcfb5de7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 19, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6660),
                            UserId = new Guid("5099b530-3bf7-47ba-b894-8291236a0198"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 20, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6660),
                            UserId = new Guid("7956c394-e9c5-4b9c-904f-954c459bad02"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 21, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6660),
                            UserId = new Guid("c35e44b0-57ef-456f-8d7a-d0a12f9df13b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 22, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6660),
                            UserId = new Guid("ac6b08e1-53e3-4364-a6af-0a7ecc299154"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 23, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6660),
                            UserId = new Guid("368c6dee-0c79-4673-b178-bf23125a7d0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 24, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6660),
                            UserId = new Guid("e61d255f-8b80-4e08-9c08-dbab8df42f17"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 25, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6660),
                            UserId = new Guid("ad4f12f8-6280-47a1-9e8f-54e97b84e792"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 26, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6660),
                            UserId = new Guid("6718d752-9569-4126-90b2-7e00f5990b0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 27, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6660),
                            UserId = new Guid("51485224-7236-4cdf-a155-76f66c3d1795"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 28, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6670),
                            UserId = new Guid("98296d73-6a0c-4da9-8362-6fa8dcfb5de7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 29, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6670),
                            UserId = new Guid("5099b530-3bf7-47ba-b894-8291236a0198"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 30, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6670),
                            UserId = new Guid("7956c394-e9c5-4b9c-904f-954c459bad02"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2023, 12, 31, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6670),
                            UserId = new Guid("c35e44b0-57ef-456f-8d7a-d0a12f9df13b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 1, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6670),
                            UserId = new Guid("ac6b08e1-53e3-4364-a6af-0a7ecc299154"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 2, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6670),
                            UserId = new Guid("368c6dee-0c79-4673-b178-bf23125a7d0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 3, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6670),
                            UserId = new Guid("e61d255f-8b80-4e08-9c08-dbab8df42f17"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 4, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6670),
                            UserId = new Guid("ad4f12f8-6280-47a1-9e8f-54e97b84e792"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 5, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6680),
                            UserId = new Guid("6718d752-9569-4126-90b2-7e00f5990b0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 6, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6680),
                            UserId = new Guid("51485224-7236-4cdf-a155-76f66c3d1795"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 7, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6680),
                            UserId = new Guid("98296d73-6a0c-4da9-8362-6fa8dcfb5de7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 8, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6680),
                            UserId = new Guid("5099b530-3bf7-47ba-b894-8291236a0198"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 9, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6680),
                            UserId = new Guid("7956c394-e9c5-4b9c-904f-954c459bad02"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 10, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6680),
                            UserId = new Guid("c35e44b0-57ef-456f-8d7a-d0a12f9df13b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 11, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6680),
                            UserId = new Guid("ac6b08e1-53e3-4364-a6af-0a7ecc299154"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6680),
                            UserId = new Guid("368c6dee-0c79-4673-b178-bf23125a7d0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 13, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6680),
                            UserId = new Guid("e61d255f-8b80-4e08-9c08-dbab8df42f17"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 14, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6690),
                            UserId = new Guid("ad4f12f8-6280-47a1-9e8f-54e97b84e792"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 15, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6690),
                            UserId = new Guid("6718d752-9569-4126-90b2-7e00f5990b0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 16, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6690),
                            UserId = new Guid("51485224-7236-4cdf-a155-76f66c3d1795"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 17, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6690),
                            UserId = new Guid("98296d73-6a0c-4da9-8362-6fa8dcfb5de7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 18, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6690),
                            UserId = new Guid("5099b530-3bf7-47ba-b894-8291236a0198"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 19, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6690),
                            UserId = new Guid("7956c394-e9c5-4b9c-904f-954c459bad02"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 20, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6690),
                            UserId = new Guid("c35e44b0-57ef-456f-8d7a-d0a12f9df13b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 21, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6690),
                            UserId = new Guid("ac6b08e1-53e3-4364-a6af-0a7ecc299154"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 22, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6690),
                            UserId = new Guid("368c6dee-0c79-4673-b178-bf23125a7d0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 23, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6690),
                            UserId = new Guid("e61d255f-8b80-4e08-9c08-dbab8df42f17"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 24, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6700),
                            UserId = new Guid("ad4f12f8-6280-47a1-9e8f-54e97b84e792"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 25, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6700),
                            UserId = new Guid("6718d752-9569-4126-90b2-7e00f5990b0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 26, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6700),
                            UserId = new Guid("51485224-7236-4cdf-a155-76f66c3d1795"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 27, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6700),
                            UserId = new Guid("98296d73-6a0c-4da9-8362-6fa8dcfb5de7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 28, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6700),
                            UserId = new Guid("5099b530-3bf7-47ba-b894-8291236a0198"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 29, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6700),
                            UserId = new Guid("7956c394-e9c5-4b9c-904f-954c459bad02"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 30, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6700),
                            UserId = new Guid("c35e44b0-57ef-456f-8d7a-d0a12f9df13b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 1, 31, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6700),
                            UserId = new Guid("ac6b08e1-53e3-4364-a6af-0a7ecc299154"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 1, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6700),
                            UserId = new Guid("368c6dee-0c79-4673-b178-bf23125a7d0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 2, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6700),
                            UserId = new Guid("e61d255f-8b80-4e08-9c08-dbab8df42f17"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 3, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6710),
                            UserId = new Guid("ad4f12f8-6280-47a1-9e8f-54e97b84e792"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 4, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6710),
                            UserId = new Guid("6718d752-9569-4126-90b2-7e00f5990b0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 5, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6710),
                            UserId = new Guid("51485224-7236-4cdf-a155-76f66c3d1795"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 6, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6710),
                            UserId = new Guid("98296d73-6a0c-4da9-8362-6fa8dcfb5de7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 7, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6710),
                            UserId = new Guid("5099b530-3bf7-47ba-b894-8291236a0198"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 8, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6710),
                            UserId = new Guid("7956c394-e9c5-4b9c-904f-954c459bad02"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 9, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6710),
                            UserId = new Guid("c35e44b0-57ef-456f-8d7a-d0a12f9df13b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 10, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6710),
                            UserId = new Guid("ac6b08e1-53e3-4364-a6af-0a7ecc299154"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 11, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6710),
                            UserId = new Guid("368c6dee-0c79-4673-b178-bf23125a7d0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6720),
                            UserId = new Guid("e61d255f-8b80-4e08-9c08-dbab8df42f17"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 13, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6720),
                            UserId = new Guid("ad4f12f8-6280-47a1-9e8f-54e97b84e792"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 14, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6720),
                            UserId = new Guid("6718d752-9569-4126-90b2-7e00f5990b0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 15, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6720),
                            UserId = new Guid("51485224-7236-4cdf-a155-76f66c3d1795"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 16, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6720),
                            UserId = new Guid("98296d73-6a0c-4da9-8362-6fa8dcfb5de7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 17, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6720),
                            UserId = new Guid("5099b530-3bf7-47ba-b894-8291236a0198"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 18, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6720),
                            UserId = new Guid("7956c394-e9c5-4b9c-904f-954c459bad02"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 19, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6720),
                            UserId = new Guid("c35e44b0-57ef-456f-8d7a-d0a12f9df13b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 20, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6720),
                            UserId = new Guid("ac6b08e1-53e3-4364-a6af-0a7ecc299154"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 21, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6720),
                            UserId = new Guid("368c6dee-0c79-4673-b178-bf23125a7d0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 22, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6730),
                            UserId = new Guid("e61d255f-8b80-4e08-9c08-dbab8df42f17"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 23, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6730),
                            UserId = new Guid("ad4f12f8-6280-47a1-9e8f-54e97b84e792"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 24, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6730),
                            UserId = new Guid("6718d752-9569-4126-90b2-7e00f5990b0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 25, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6730),
                            UserId = new Guid("51485224-7236-4cdf-a155-76f66c3d1795"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 26, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6730),
                            UserId = new Guid("98296d73-6a0c-4da9-8362-6fa8dcfb5de7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 27, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6730),
                            UserId = new Guid("5099b530-3bf7-47ba-b894-8291236a0198"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 28, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6730),
                            UserId = new Guid("7956c394-e9c5-4b9c-904f-954c459bad02"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 2, 29, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6730),
                            UserId = new Guid("c35e44b0-57ef-456f-8d7a-d0a12f9df13b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 1, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6730),
                            UserId = new Guid("ac6b08e1-53e3-4364-a6af-0a7ecc299154"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 2, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6730),
                            UserId = new Guid("368c6dee-0c79-4673-b178-bf23125a7d0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 3, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6740),
                            UserId = new Guid("e61d255f-8b80-4e08-9c08-dbab8df42f17"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 4, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6740),
                            UserId = new Guid("ad4f12f8-6280-47a1-9e8f-54e97b84e792"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 5, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6740),
                            UserId = new Guid("6718d752-9569-4126-90b2-7e00f5990b0a"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 6, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6740),
                            UserId = new Guid("51485224-7236-4cdf-a155-76f66c3d1795"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 7, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6740),
                            UserId = new Guid("98296d73-6a0c-4da9-8362-6fa8dcfb5de7"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 8, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6740),
                            UserId = new Guid("5099b530-3bf7-47ba-b894-8291236a0198"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 9, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6740),
                            UserId = new Guid("7956c394-e9c5-4b9c-904f-954c459bad02"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 10, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6740),
                            UserId = new Guid("c35e44b0-57ef-456f-8d7a-d0a12f9df13b"),
                            Steps = 1000
                        },
                        new
                        {
                            Date = new DateTime(2024, 3, 11, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6740),
                            UserId = new Guid("ac6b08e1-53e3-4364-a6af-0a7ecc299154"),
                            Steps = 1000
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.SuperUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("password");

                    b.Property<string>("SuperRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("super_role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("SuperUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ed0e5b0e-c49b-45db-89a2-e6cf6ba46170"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 279, DateTimeKind.Local).AddTicks(780),
                            Password = "$2a$05$byED3tyE5RJ8kwWg19fDuuQivzPwrJrTqKeC/RKyNV2dlffOhvFAi",
                            SuperRole = "superAdmin",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 279, DateTimeKind.Local).AddTicks(790),
                            Username = "superAdmin"
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("368c6dee-0c79-4673-b178-bf23125a7d0a"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6030),
                            Identifier = "user0",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6080)
                        },
                        new
                        {
                            Id = new Guid("e61d255f-8b80-4e08-9c08-dbab8df42f17"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6090),
                            Identifier = "user1",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6090)
                        },
                        new
                        {
                            Id = new Guid("ad4f12f8-6280-47a1-9e8f-54e97b84e792"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6100),
                            Identifier = "user2",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6100)
                        },
                        new
                        {
                            Id = new Guid("6718d752-9569-4126-90b2-7e00f5990b0a"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6100),
                            Identifier = "user3",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6110)
                        },
                        new
                        {
                            Id = new Guid("51485224-7236-4cdf-a155-76f66c3d1795"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6110),
                            Identifier = "user4",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6110)
                        },
                        new
                        {
                            Id = new Guid("98296d73-6a0c-4da9-8362-6fa8dcfb5de7"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6120),
                            Identifier = "user5",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6120)
                        },
                        new
                        {
                            Id = new Guid("5099b530-3bf7-47ba-b894-8291236a0198"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6130),
                            Identifier = "user6",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6130)
                        },
                        new
                        {
                            Id = new Guid("7956c394-e9c5-4b9c-904f-954c459bad02"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6140),
                            Identifier = "user7",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6140)
                        },
                        new
                        {
                            Id = new Guid("c35e44b0-57ef-456f-8d7a-d0a12f9df13b"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6150),
                            Identifier = "user8",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6150)
                        },
                        new
                        {
                            Id = new Guid("ac6b08e1-53e3-4364-a6af-0a7ecc299154"),
                            CreatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6150),
                            Identifier = "user9",
                            UpdatedAt = new DateTime(2024, 3, 12, 21, 33, 37, 275, DateTimeKind.Local).AddTicks(6150)
                        });
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Badge", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.User", null)
                        .WithMany("Badges")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.BadgesToUser", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarFitApi.Models.Database.User", "User")
                        .WithMany("BadgesToUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Challenge", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.Badge", "Badge")
                        .WithMany("Challenges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.DayOfWalk", b =>
                {
                    b.HasOne("StarFitApi.Models.Database.User", "User")
                        .WithMany("DaysOfWalk")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.Badge", b =>
                {
                    b.Navigation("Challenges");
                });

            modelBuilder.Entity("StarFitApi.Models.Database.User", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("BadgesToUsers");

                    b.Navigation("DaysOfWalk");
                });
#pragma warning restore 612, 618
        }
    }
}
